// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "TransformTypes.h"
#include "ToolContextInterfaces.h"

class UMaterialInterface;
class UInteractiveToolManager;
struct FMeshDescription;
PREDECLARE_USE_GEOMETRY_CLASS(FDynamicMesh3);
class AActor;
class UPrimitiveComponent;
class UTexture2D;

class MODELINGCOMPONENTS_API IAssetGenerationAPI
{
public:
	virtual ~IAssetGenerationAPI(){}

	/**
	 * Create a new UStaticMeshAsset for the provided mesh, then a new UStaticMeshComponent and AStaticMeshActor in the TargetWorld
	 * @param TargetWorld world to create new Actor in
	 * @param Transform transform to set on Actor
	 * @param ObjectBaseName a base name for the Asset and Actor. Unique name will be generated by appending a number, if a name collision occurs.
	 * @param AssetConfig configuration information for the new Asset
	 * @return new AStaticMeshActor with new Asset assigned to it's UStaticMeshComponent
	 * @warning this function may return null. In this case the asset creation failed and/or the user cancelled during the process, if it was interactive.
	 */
	virtual AActor* GenerateStaticMeshActor(
		UWorld* TargetWorld,
		FTransform Transform,
		FString ObjectBaseName,
		FGeneratedStaticMeshAssetConfig&& AssetConfig) = 0;


	/**
	 * Save a generated UTexture2D as an Asset.
	 * Assumption is that the texture was generated in code and is in the Transient package.
	 * @param GeneratedTexture Texture2D to save
	 * @param ObjectBaseName a base name for the Asset. Unique name will be generated by appending a number, if a name collision occurs.
	 * @param RelativeToAsset New texture will be saved at the same path as the UPackage for this UObject, which we assume to be an Asset (eg like a UStaticMesh)
	 */
	virtual bool SaveGeneratedTexture2D(
		UTexture2D* GeneratedTexture,
		FString ObjectBaseName,
		const UObject* RelativeToAsset)
	{
		check(false); return false;
	}
};

/**
 * Utility functions for generating Assets in InteractiveTool implementations
 */
namespace AssetGenerationUtil
{
	/**
	 * Creates a new StaticMesh actor/component, with a new mesh asset stored at the given PackagePath created via the AssetAPI
	 * @param AssetAPI pointer to context asset API that will be used to create new asset
	 * @param TargetWorld world that Actor will be created in
	 * @param Mesh geometry for the mesh
	 * @param Transform transformation for the new actor
	 * @param ObjectName name of the new asset
	 * @param PackagePath path of the new asset
	 * @param Material optional single material to set on actor
	 * @return new mesh actor
	 */
	MODELINGCOMPONENTS_API AActor* GenerateStaticMeshActor(
		IAssetGenerationAPI* AssetAPI,
		UWorld* TargetWorld,
		const FDynamicMesh3* Mesh,
		const UE::Geometry::FTransform3d& Transform,
		FString ObjectName,
		UMaterialInterface* Material = nullptr
	);

	/**
	* Creates a new StaticMesh actor/component, with a new mesh asset stored at the given PackagePath created via the AssetAPI
	* @param AssetAPI pointer to context asset API that will be used to create new asset
	* @param TargetWorld world that Actor will be created in
	* @param Mesh geometry for the mesh
	* @param Transform transformation for the new actor
	* @param ObjectName name of the new asset
	* @param PackagePath path of the new asset
	* @param Materials materials to set on generated actor
	* @return new mesh actor
	*/
	MODELINGCOMPONENTS_API AActor* GenerateStaticMeshActor(
		IAssetGenerationAPI* AssetAPI,
		UWorld* TargetWorld,
		const FDynamicMesh3* Mesh,
		const UE::Geometry::FTransform3d& Transform,
		FString ObjectName,
		const TArrayView<UMaterialInterface*>& Materials
	);


	/**
	 * Save generated UTexture2D that is currently in the Transient package (ie generated in code) as an Asset with a given name 
	 * @param AssetAPI pointer to context asset API that will be used to create new asset
	 * @param TransientTexture texture to save
	 * @param ObjectName name of the new asset
	 * @param RelativeToAsset New texture will be saved at the same path as the UPackage for this UObject, which we assume to be an Asset (eg like a UStaticMesh)
	 */
	MODELINGCOMPONENTS_API bool SaveGeneratedTexture2D(
		IAssetGenerationAPI* AssetAPI,
		UTexture2D* TransientTexture,
		FString ObjectName,
		const UObject* RelativeToAsset);

	/**
	 * Strip the appended auto-generated _UUID suffix on the given string, if we can detect one
	 * @param InputName input string that may have _UUID suffix
	 * @return InputName without _UUID suffix
	 */
	MODELINGCOMPONENTS_API FString StripGeneratedAssetSuffixFromName(
		FString InputName);

	/**
	 * Look up the name for the Asset underlying the given Component, if there is one.
	 * Optionally Strip off the appended auto-generated UUID string if we can detect one.
	 * If there is not a known underlying asset, returns the Component's name
	 * @param Component the Component we want the Asset Base Name for
	 * @param bRemoveAutoGeneratedSuffixes strip off generated UUID suffix if one is detected (default true)
	 * @return the Name for the Component
	 */
	MODELINGCOMPONENTS_API FString GetComponentAssetBaseName(
		UPrimitiveComponent* Component, 
		bool bRemoveAutoGeneratedSuffixes = true);


}
