// Copyright Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	LumenVoxelDistanceFieldCommon.ush
=============================================================================*/

struct FVoxelDistanceField
{
	uint Distance;
	uint FaceMask;

	void Unpack(uint4 V)
	{
		Distance = V.x;
		FaceMask = V.y;
	}

	uint4 Pack()
	{
		uint4 V;
		V.x = Distance;
		V.y = FaceMask;
		V.z = 0;
		V.w = 0;

		return V;
	}
};
