// Copyright Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	VulkanCommon.usf: Common Vulkan shader code
=============================================================================*/

// Update this GUID to improve shader recompilation for Vulkan only shaders
// GUID = F1EAFBAF-17ED-4845-8FA3-F640F48665E6
// Glslang 1.1.82.1

#pragma once
