// Copyright 1998-2019 Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	VulkanCommon.usf: Common Vulkan shader code
=============================================================================*/

// Update this GUID to improve shader recompilation for Vulkan only shaders
// GUID = BFB17533-00ED-4766-BFB1-0B8421A9B21A
// Glslang 1.1.82.1

#pragma once
