// Copyright 1998-2019 Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	VulkanCommon.usf: Common Vulkan shader code
=============================================================================*/

// Update this GUID to improve shader recompilation for Vulkan only shaders
// GUID = {EDAF647B-ED20-440B-BE20-F5F9949CF71A}
// Glslang 1.1.82.1

#pragma once
