// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "ModelingToolsEditorModeSettings.generated.h"


UENUM()
enum class EModelingModeAssetGenerationBehavior
{
	/** Generate and automatically Save new Assets on creation */
	AutoGenerateAndAutosave,

	/** Generate new Assets and mark as Modified but do not automatically Save */
	AutoGenerateButDoNotAutosave,

	/** Prompt to Save each new Asset upon Creation */
	InteractivePromptToSave
};



UENUM()
enum class EModelingModeAssetGenerationLocation
{
	/** All generated assets will be stored in an AutoGenerated folder that is located relative to the World they are being saved in */
	AutoGeneratedWorldRelativeAssetPath,

	/** All generated assets will be stored in a root-level AutoGenerated folder */
	AutoGeneratedGlobalAssetPath,

	/** Generated assets will be stored in the currently-visible Asset Browser folder if available, otherwise at the Auto Generated Asset Path */
	CurrentAssetBrowserPathIfAvailable
};


/**
 * Settings for the Modeling Tools Editor Mode plug-in.
 */
UCLASS(config=Editor)
class MODELINGTOOLSEDITORMODE_API UModelingToolsEditorModeSettings
	: public UObject
{
	GENERATED_BODY()
public:

	/** How should Assets auto-generated by Modeling Tools be handled in terms of saving, naming, etc */
	UPROPERTY(config, EditAnywhere, Category = GeneratedModelingAssets)
	EModelingModeAssetGenerationBehavior AssetGenerationMode = EModelingModeAssetGenerationBehavior::AutoGenerateButDoNotAutosave;

	/** Where should Assets auto-generated by Modeling Tools be stored by default */
	UPROPERTY(config, EditAnywhere, Category = GeneratedModelingAssets)
	EModelingModeAssetGenerationLocation AssetGenerationLocation = EModelingModeAssetGenerationLocation::AutoGeneratedWorldRelativeAssetPath;

	/** Assets auto-generated by Modeling Tools are stored at this path, relative to the parent path defined by the Location. Set to an empty string to disable. */
	UPROPERTY(config, EditAnywhere, Category = GeneratedModelingAssets)
	FString AutoGeneratedAssetPath = TEXT("_GENERATED");

	/** If true, Auto-Generated Assets created in an unsaved Level will be stored relative to top-level /Game folder, otherwise they will be stored in /Temp and cannot be saved until they are explicitly moved to a permanent location */
	UPROPERTY(config, EditAnywhere, Category = GeneratedModelingAssets)
	bool bStoreUnsavedLevelAssetsInTopLevelGameFolder = true;

	/** If true, Autogenerated Assets are stored in per-user folders below the Autogen path */
	UPROPERTY(config, EditAnywhere, Category = GeneratedModelingAssets)
	bool bUsePerUserAutogenSubfolder = true;

	/** If true, Autogenerated Assets have a short random string generated and appended to their name */
	UPROPERTY(config, EditAnywhere, Category = GeneratedModelingAssets)
	bool bAppendRandomStringToName = true;

public:

	DECLARE_MULTICAST_DELEGATE_TwoParams(UModelingToolsEditorModeSettingsModified, UObject*, FProperty*);
	UModelingToolsEditorModeSettingsModified OnModified;

	void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent)
	{
		OnModified.Broadcast(this, PropertyChangedEvent.Property);
	}

};
