// Copyright Epic Games, Inc. All Rights Reserved.

#include "Modules/ModuleInterface.h"
#include "Modules/ModuleManager.h"
#include "Interfaces/IPluginManager.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "VCamModifier.h"

class FVCamCoreEditorModule : public IModuleInterface
{
public:

	// IModuleInterface interface

	virtual void StartupModule() override
	{
		RegisterAutoGeneratedDefaultEvents();
	};
	
	virtual void ShutdownModule() override
	{
		
	};

	// Set up default nodes for VCam Core blueprint classes
	void RegisterAutoGeneratedDefaultEvents()
	{
		FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, UVCamBlueprintModifier::StaticClass(), "OnInitialize");
		FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, UVCamBlueprintModifier::StaticClass(), "OnApply");
	}	
};

IMPLEMENT_MODULE(FVCamCoreEditorModule, VCamCoreEditor);