// Copyright Epic Games, Inc. All Rights Reserved.

#include "Modules/ModuleInterface.h"
#include "Modules/ModuleManager.h"

#include "Customizations/ConnectionTargetSettingsTypeCustomization.h"
#include "Customizations/VCamBaseActorCustomization.h"
#include "Customizations/VCamInputProfileCustomization.h"
#include "Customizations/StateSwitcher/WidgetConnectionConfigTypeCustomization.h"
#include "UI/Switcher/WidgetConnectionConfig.h"
#include "VCamBaseActor.h"
#include "VCamComponent.h"
#include "VCamModifier.h"

#include "Interfaces/IPluginManager.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "PropertyEditorModule.h"

namespace UE::VCamCoreEditor::Private
{
	class FVCamCoreEditorModule : public IModuleInterface
	{
	public:

		// IModuleInterface interface

		virtual void StartupModule() override
		{
			RegisterAutoGeneratedDefaultEvents();
		
			FPropertyEditorModule& PropertyModule = FModuleManager::GetModuleChecked<FPropertyEditorModule>("PropertyEditor");

			PropertyModule.RegisterCustomPropertyTypeLayout(
				FVCamInputProfile::StaticStruct()->GetFName(),
				FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FVCamInputProfileCustomization::MakeInstance)
				);
			PropertyModule.RegisterCustomPropertyTypeLayout(
				FVCamConnectionTargetSettings::StaticStruct()->GetFName(),
				FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FConnectionTargetSettingsTypeCustomization::MakeInstance)
				);
			PropertyModule.RegisterCustomPropertyTypeLayout(
				FWidgetConnectionConfig::StaticStruct()->GetFName(), 
				FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FWidgetConnectionConfigTypeCustomization::MakeInstance)
				);
			
			PropertyModule.RegisterCustomClassLayout(
				AVCamBaseActor::StaticClass()->GetFName(),
				FOnGetDetailCustomizationInstance::CreateStatic(&FVCamBaseActorCustomization::MakeInstance)
				);
		};
	
		virtual void ShutdownModule() override
		{
			FPropertyEditorModule& PropertyModule = FModuleManager::GetModuleChecked<FPropertyEditorModule>("PropertyEditor");
			PropertyModule.UnregisterCustomPropertyTypeLayout("VCamInputProfile");
		};

		// Set up default nodes for VCam Core blueprint classes
		void RegisterAutoGeneratedDefaultEvents()
		{
			FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, UVCamBlueprintModifier::StaticClass(), "OnInitialize");
			FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, UVCamBlueprintModifier::StaticClass(), "OnDeinitialize");
			FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, UVCamBlueprintModifier::StaticClass(), "OnApply");
		}	
	};
}

IMPLEMENT_MODULE(UE::VCamCoreEditor::Private::FVCamCoreEditorModule, VCamCoreEditor);