// Copyright Epic Games, Inc. All Rights Reserved.

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum EDatasmithFacadeMaterialExpressionType {
  None = 0,
  ConstantBool = 1 << 0,
  ConstantColor = 1 << 1,
  ConstantScalar = 1 << 2,
  FlattenNormal = 1 << 3,
  FunctionCall = 1 << 4,
  Generic = 1 << 5,
  Texture = 1 << 6,
  TextureCoordinate = 1 << 7
}
