// Copyright Epic Games, Inc. All Rights Reserved.

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class FDatasmithFacadeScene : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FDatasmithFacadeScene(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FDatasmithFacadeScene obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FDatasmithFacadeScene() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DatasmithFacadeCSharpPINVOKE.delete_FDatasmithFacadeScene(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public FDatasmithFacadeScene(string InApplicationHostName, string InApplicationVendorName, string InApplicationProductName, string InApplicationProductVersion) : this(DatasmithFacadeCSharpPINVOKE.new_FDatasmithFacadeScene(InApplicationHostName, InApplicationVendorName, InApplicationProductName, InApplicationProductVersion), true) {
  }

  public void AddActor(FDatasmithFacadeActor InActorPtr) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_AddActor(swigCPtr, FDatasmithFacadeActor.getCPtr(InActorPtr));
  }

  public int GetActorsCount() {
    int ret = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_GetActorsCount(swigCPtr);
    return ret;
  }

  public FDatasmithFacadeActor GetActor(int ActorIndex) {
	global::System.IntPtr objectPtr = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_GetActor(swigCPtr, ActorIndex);
	if(objectPtr == global::System.IntPtr.Zero)
	{
		return null;
	}
	else
	{
		FDatasmithFacadeActor.EActorType ActorType = (new FDatasmithFacadeActor(objectPtr, false)).GetActorType();

		switch(ActorType)
		{
		case FDatasmithFacadeActor.EActorType.DirectionalLight:
			return new FDatasmithFacadeDirectionalLight(objectPtr, true);
		case FDatasmithFacadeActor.EActorType.AreaLight:
			return new FDatasmithFacadeAreaLight(objectPtr, true);
		case FDatasmithFacadeActor.EActorType.LightmassPortal:
			return new FDatasmithFacadeLightmassPortal(objectPtr, true);
		case FDatasmithFacadeActor.EActorType.PointLight:
			return new FDatasmithFacadePointLight(objectPtr, true);
		case FDatasmithFacadeActor.EActorType.SpotLight:
			return new FDatasmithFacadeSpotLight(objectPtr, true);
		case FDatasmithFacadeActor.EActorType.StaticMeshActor:
			return new FDatasmithFacadeActorMesh(objectPtr, true);
		case FDatasmithFacadeActor.EActorType.Camera:
			return new FDatasmithFacadeActorCamera(objectPtr, true);
		case FDatasmithFacadeActor.EActorType.Actor:
			return new FDatasmithFacadeActor(objectPtr, true);
		case FDatasmithFacadeActor.EActorType.Unsupported:
		default:
			return null;
		}
	}
}

  public void RemoveActor(FDatasmithFacadeActor InActorPtr, FDatasmithFacadeScene.EActorRemovalRule RemovalRule) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_RemoveActor__SWIG_0(swigCPtr, FDatasmithFacadeActor.getCPtr(InActorPtr), (int)RemovalRule);
  }

  public void RemoveActor(FDatasmithFacadeActor InActorPtr) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_RemoveActor__SWIG_1(swigCPtr, FDatasmithFacadeActor.getCPtr(InActorPtr));
  }

  public void AddMaterial(FDatasmithFacadeBaseMaterial InMaterialPtr) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_AddMaterial(swigCPtr, FDatasmithFacadeBaseMaterial.getCPtr(InMaterialPtr));
  }

  public int GetMaterialsCount() {
    int ret = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_GetMaterialsCount(swigCPtr);
    return ret;
  }

  public FDatasmithFacadeBaseMaterial GetMaterial(int MaterialIndex) {
	global::System.IntPtr objectPtr = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_GetMaterial(swigCPtr, MaterialIndex);
	if(objectPtr == global::System.IntPtr.Zero)
	{
		return null;
	}
	else
	{
		FDatasmithFacadeBaseMaterial.EDatasmithMaterialType MaterialType = (new FDatasmithFacadeBaseMaterial(objectPtr, false)).GetDatasmithMaterialType();

		switch(MaterialType)
		{
		case FDatasmithFacadeBaseMaterial.EDatasmithMaterialType.UEPbrMaterial:
			return new FDatasmithFacadeUEPbrMaterial(objectPtr, true);
		case FDatasmithFacadeBaseMaterial.EDatasmithMaterialType.MasterMaterial:
			return new FDatasmithFacadeMasterMaterial(objectPtr, true);
		case FDatasmithFacadeBaseMaterial.EDatasmithMaterialType.Unsupported:
		default:
			return null;
		}
	}
}

  public void RemoveMaterial(FDatasmithFacadeBaseMaterial InMaterialPtr) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_RemoveMaterial(swigCPtr, FDatasmithFacadeBaseMaterial.getCPtr(InMaterialPtr));
  }

  public void AddMesh(FDatasmithFacadeMesh InMeshPtr) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_AddMesh(swigCPtr, FDatasmithFacadeMesh.getCPtrAndDisown(InMeshPtr));
  }

  public void AddTexture(FDatasmithFacadeTexture InTexturePtr) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_AddTexture(swigCPtr, FDatasmithFacadeTexture.getCPtr(InTexturePtr));
  }

  public int GetTexturesCount() {
    int ret = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_GetTexturesCount(swigCPtr);
    return ret;
  }

  public FDatasmithFacadeTexture GetTexture(int TextureIndex) {
    global::System.IntPtr cPtr = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_GetTexture(swigCPtr, TextureIndex);
    FDatasmithFacadeTexture ret = (cPtr == global::System.IntPtr.Zero) ? null : new FDatasmithFacadeTexture(cPtr, false);
    return ret;
  }

  public void RemoveTexture(FDatasmithFacadeTexture InTexturePtr) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_RemoveTexture(swigCPtr, FDatasmithFacadeTexture.getCPtr(InTexturePtr));
  }

  public void AddMetaData(FDatasmithFacadeMetaData InMetaDataPtr) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_AddMetaData(swigCPtr, FDatasmithFacadeMetaData.getCPtr(InMetaDataPtr));
  }

  public int GetMetaDataCount() {
    int ret = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_GetMetaDataCount(swigCPtr);
    return ret;
  }

  public FDatasmithFacadeMetaData GetMetaData(int MetaDataIndex) {
	global::System.IntPtr objectPtr = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_GetMetaData(swigCPtr, MetaDataIndex);
	if(objectPtr == global::System.IntPtr.Zero)
	{
		return null;
	}
	else
	{
		return new FDatasmithFacadeMetaData(objectPtr, true);
	}
}

  public void RemoveMetaData(FDatasmithFacadeMetaData InMetaDataPtr) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_RemoveMetaData(swigCPtr, FDatasmithFacadeMetaData.getCPtr(InMetaDataPtr));
  }

  public void PreExport() {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_PreExport(swigCPtr);
  }

  public static void Shutdown() {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_Shutdown();
  }

  public void ExportScene(string InOutputPath) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_ExportScene(swigCPtr, InOutputPath);
  }

  public void ExportAssets(string InAssetFolder) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_ExportAssets(swigCPtr, InAssetFolder);
  }

  public void BuildScene(string InSceneName) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_BuildScene(swigCPtr, InSceneName);
  }

  public void SetLabel(string InSceneLabel) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_SetLabel(swigCPtr, InSceneLabel);
  }

  public string GetLabel() {
    string ret = global::System.Runtime.InteropServices.Marshal.PtrToStringUni(DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeScene_GetLabel(swigCPtr));
    return ret;
  }

  public enum EActorRemovalRule {
    RemoveChildren,
    KeepChildrenAndKeepRelativeTransform
  }

}
