// Copyright 1998-2019 Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	HoloLensTargetSettings.h: Declares the UHoloLensTargetSettings class.
=============================================================================*/

#pragma once

#include "WindowsTargetSettings.h"
#include "HoloLensLocalizedResources.h"
#include "HoloLensTargetSettings.generated.h"

USTRUCT()
struct FHoloLensDLCSettings
{
public:
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, config, Category = DLC)
	FString PluginName;

	UPROPERTY(EditAnywhere, config, Category = DLC, Meta = (DisplayName = "Package/Identity/Name"))
	FString PackageIdentityName;

	UPROPERTY(EditAnywhere, config, Category = DLC, Meta = (DisplayName = "Package/Identity/Version"))
	FString PackageIdentityVersion;
};

/**
 * Implements the settings for the HoloLens target platform.
 */
UCLASS(config = Engine, defaultconfig)
class UHoloLensTargetSettings
	: public UObject
{
public:

	GENERATED_UCLASS_BODY()

	virtual const TCHAR* GetConfigOverridePlatform() const override
	{
		return TEXT("HoloLens");
	}

	virtual void PostInitProperties() override;

	/**
	 * When checked, a build that can be run via emulation is added
	 */
	UPROPERTY(EditAnywhere, Config, Category="HoloLens", Meta=(DisplayName="Build for HoloLens Emulation"))
	bool bBuildForEmulation = false;

	/**
	 * When the box checked the final bundle has binaries of ARM64 OSes.
	 */
	UPROPERTY(EditAnywhere, Config, Category="HoloLens", Meta=(DisplayName="Build for HoloLens Device"))
	bool bBuildForDevice = true;

	/**
	 * HoloLens includes SM4 support (D3D Feature level 10) by default.  This setting excludes this
	 * support, possibly reducing package size, but limiting the range of devices the package
	 * will run on.  Currently you must leave this DISABLED if you wish to run as HoloLens on Xbox One.
	 */
	UPROPERTY(EditAnywhere, config, Category = Rendering, Meta=(DisplayName="Exclude Shader Model 4 Support"))
	bool bExcludeShaderModel4Support;

	/**
	 * Selects whether to build the D3D12 RHI module.  The D3D12 RHI may have requirements for minimum supported
	 * Windows SDK version and compiler toolset beyond the defaults for HoloLens support.  D3D11 support is always
	 * included in the final exe regardless of this setting.
	 */
	UPROPERTY(EditAnywhere, config, Category = Rendering, Meta = (DisplayName = "Build with D3D12 support"))
	bool bBuildD3D12RHI;

	/**
	 * Selects whether to use the D3D12 RHI by default at runtime.  Requires that the exe is build with D3D12 support enabled.
	 */
	UPROPERTY(EditAnywhere, config, Category = Rendering, Meta=(DisplayName = "Run using D3D12 RHI", editcondition="bBuildD3D12RHI"))
	bool bUseD3D12RHI;

	/**
	 * Whether cooked content should be copied into the loose package image generated by deploy from Visual Studio.
	 */
	UPROPERTY(EditAnywhere, config, Category = "Toolchain", Meta = (DisplayName = "Copy Cooked Content for F5 Deployment"))
	bool bCopyCookedContentForF5Deployment;

	/**
	 * Controls whether to use the retail Windows Store environment for license checks.  This must be turned on
	 * when building for submission to the Windows Store, or when sideloading outside of Developer Mode.  Note,
	 * however, that testing a build with this flag enables requires that the product is listed in the retail
	 * catalog for the Windows Store.
	 */
	UPROPERTY(EditAnywhere, config, Category = "Packaging", AdvancedDisplay, Meta = (DisplayName = "Use Retail Windows Store Environment"))
	bool bBuildForRetailWindowsStore;

	UPROPERTY(EditAnywhere, config, Category = "Rendering", meta = (DisplayName = "Enable PIX Profiling"))
	bool bEnablePIXProfiling;

	UPROPERTY(EditAnywhere, config, Category = Packaging, meta=(HideAlphaChannel))
	FColor TileBackgroundColor = FColor::FromHex(FString("#000040"));

	UPROPERTY(EditAnywhere, config, Category = Packaging, meta=(HideAlphaChannel))
	FColor SplashScreenBackgroundColor = FColor::FromHex(FString("#000040"));

	UPROPERTY(EditAnywhere, config, Category = Packaging)
	TArray<FHoloLensCorePackageLocalizedResources> PerCultureResources;

	/**
	 * Identifies the device family that your package will target.
	 */
	UPROPERTY(EditAnywhere, config, Category = "OS Info")
	FString TargetDeviceFamily;

	/**
	 * Minimum version of the HoloLens platform required to run this title.
	 * It will not be possible to deploy the build on earlier versions.
	 */
	UPROPERTY(EditAnywhere, config, Category = "OS Info", Meta = (DisplayName = "Minimum supported platform version"))
	FString MinimumPlatformVersion;

	/**
	 * Specifies the maximum version of the universal platform on which the
	 * title is known to work as expected.  When deployed to later versions
	 * the title will experience the runtime behavior of the version given here.
	 */
	UPROPERTY(EditAnywhere, config, Category = "OS Info", Meta = (DisplayName = "Maximum tested platform version"))
	FString MaximumPlatformVersionTested;

	/** Used by the HoloLens to indicate triangle density when generating meshes. Defaults to 500 per cubic meter */
	UPROPERTY(EditAnywhere, Config, Category="Spatial Mapping")
	float MaxTrianglesPerCubicMeter;

	/** Used by the HoloLens to indicate how large (in meters) of a volume to use for generating meshes. Defaults to a 20m cube */
	UPROPERTY(EditAnywhere, Config, Category = "Spatial Mapping")
	float SpatialMeshingVolumeSize;

	/**
	 * Package Assets into a separate file for reducing upload size.
	 */
	UPROPERTY(EditAnywhere, config, Category = Packaging, Meta = (DisplayName = "Package assets into a separate file"))
	bool bUseAssetPackage = false;

	/** The compiler version to use for this project. May be different to the chosen IDE. */
	UPROPERTY(EditAnywhere, config, Category = "Toolchain", Meta = (DisplayName = "Compiler Version"))
	ECompilerVersion CompilerVersion;

	UPROPERTY(EditAnywhere, config, Category = "Toolchain", Meta = (DisplayName = "Windows 10 SDK Version"))
	FString Windows10SDKVersion;

	/**
	 * List of supported <Capability><Capability> elements for the application.
	 */
	UPROPERTY(EditAnywhere, config, Category = Capabilities)
	TArray<FString> CapabilityList;

	/**
	 * List of supported <Capability><DeviceCapability> elements for the application.
	 */
	UPROPERTY(EditAnywhere, config, Category = Capabilities)
	TArray<FString> DeviceCapabilityList;

	/**
	 * List of supported <Capability><uap:Capability> elements for the application.
	 */
	UPROPERTY(EditAnywhere, config, Category = Capabilities)
	TArray<FString> UapCapabilityList;

	/**
	 * List of supported <Capability><uap2:Capability> elements for the application.
	 */
	UPROPERTY(EditAnywhere, config, Category = Capabilities)
	TArray<FString> Uap2CapabilityList;

	/**
	 * Set default capabilities (InternetClientServer and PrivateNetworkClientServer) for the application.
	 */
	UPROPERTY(EditAnywhere, config, Category = Capabilities)
	bool bSetDefaultCapabilities = true;

	UPROPERTY(EditAnywhere, config, Category = DLC)
	TArray<FHoloLensDLCSettings> DLCStoreMapping;

	UPROPERTY(EditAnywhere, config, Category = DLC)
	TArray<FHoloLensDlcLocalizedResources> DLCPerCultureResources;
};
