// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#if !defined(WITH_MLSDK) || WITH_MLSDK

#include "Lumin/CAPIShims/LuminAPI.h"

LUMIN_THIRD_PARTY_INCLUDES_START
#include <ml_persistent_coordinate_frames.h>
LUMIN_THIRD_PARTY_INCLUDES_END

namespace LUMIN_MLSDK_API
{

CREATE_FUNCTION_SHIM(ml_perception_client, MLResult, MLPersistentCoordinateFrameTrackerCreate)
#define MLPersistentCoordinateFrameTrackerCreate ::LUMIN_MLSDK_API::MLPersistentCoordinateFrameTrackerCreateShim
CREATE_FUNCTION_SHIM(ml_perception_client, MLResult, MLPersistentCoordinateFrameGetCount)
#define MLPersistentCoordinateFrameGetCount ::LUMIN_MLSDK_API::MLPersistentCoordinateFrameGetCountShim
CREATE_DEPRECATED_MSG_SHIM(ml_perception_client, MLResult, MLPersistentCoordinateFrameGetAll, "Replaced by MLPersistentCoordinateFrameGetAllEx.")
#define MLPersistentCoordinateFrameGetAll ::LUMIN_MLSDK_API::MLPersistentCoordinateFrameGetAllShim
CREATE_FUNCTION_SHIM(ml_perception_client, MLResult, MLPersistentCoordinateFrameGetAllEx)
#define MLPersistentCoordinateFrameGetAllEx ::LUMIN_MLSDK_API::MLPersistentCoordinateFrameGetAllExShim
CREATE_FUNCTION_SHIM(ml_perception_client, MLResult, MLPersistentCoordinateFrameGetClosest)
#define MLPersistentCoordinateFrameGetClosest ::LUMIN_MLSDK_API::MLPersistentCoordinateFrameGetClosestShim
CREATE_FUNCTION_SHIM(ml_perception_client, MLResult, MLPersistentCoordinateFrameQuery)
#define MLPersistentCoordinateFrameQuery ::LUMIN_MLSDK_API::MLPersistentCoordinateFrameQueryShim
CREATE_FUNCTION_SHIM(ml_perception_client, MLResult, MLPersistentCoordinateFrameTrackerDestroy)
#define MLPersistentCoordinateFrameTrackerDestroy ::LUMIN_MLSDK_API::MLPersistentCoordinateFrameTrackerDestroyShim
CREATE_FUNCTION_SHIM(ml_perception_client, const char*, MLPersistentCoordinateFrameGetResultString)
#define MLPersistentCoordinateFrameGetResultString ::LUMIN_MLSDK_API::MLPersistentCoordinateFrameGetResultStringShim
CREATE_FUNCTION_SHIM(ml_perception_client, MLResult, MLPersistentCoordinateFramesGetFrameState)
#define MLPersistentCoordinateFramesGetFrameState ::LUMIN_MLSDK_API::MLPersistentCoordinateFramesGetFrameStateShim

}

#endif // !defined(WITH_MLSDK) || WITH_MLSDK
