// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#if !defined(WITH_MLSDK) || WITH_MLSDK

#include "Lumin/CAPIShims/LuminAPI.h"

LUMIN_THIRD_PARTY_INCLUDES_START
#include <ml_media_common.h>
#include <ml_media_format.h>
LUMIN_THIRD_PARTY_INCLUDES_END

namespace LUMIN_MLSDK_API
{

CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_AAC_Encoded_Target_Level)
#define MLMediaFormat_Key_AAC_Encoded_Target_Level ::LUMIN_MLSDK_API::MLMediaFormat_Key_AAC_Encoded_Target_LevelShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_AAC_DRC_Boost_Factor)
#define MLMediaFormat_Key_AAC_DRC_Boost_Factor ::LUMIN_MLSDK_API::MLMediaFormat_Key_AAC_DRC_Boost_FactorShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_AAC_DRC_Attenuation_Factor)
#define MLMediaFormat_Key_AAC_DRC_Attenuation_Factor ::LUMIN_MLSDK_API::MLMediaFormat_Key_AAC_DRC_Attenuation_FactorShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_AAC_DRC_Heavy_Compression)
#define MLMediaFormat_Key_AAC_DRC_Heavy_Compression ::LUMIN_MLSDK_API::MLMediaFormat_Key_AAC_DRC_Heavy_CompressionShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_AAC_DRC_Target_Reference_Level)
#define MLMediaFormat_Key_AAC_DRC_Target_Reference_Level ::LUMIN_MLSDK_API::MLMediaFormat_Key_AAC_DRC_Target_Reference_LevelShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_AAC_Max_Output_Channel_Count)
#define MLMediaFormat_Key_AAC_Max_Output_Channel_Count ::LUMIN_MLSDK_API::MLMediaFormat_Key_AAC_Max_Output_Channel_CountShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_AAC_Profile)
#define MLMediaFormat_Key_AAC_Profile ::LUMIN_MLSDK_API::MLMediaFormat_Key_AAC_ProfileShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_AAC_SBR_Mode)
#define MLMediaFormat_Key_AAC_SBR_Mode ::LUMIN_MLSDK_API::MLMediaFormat_Key_AAC_SBR_ModeShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Bit_Rate)
#define MLMediaFormat_Key_Bit_Rate ::LUMIN_MLSDK_API::MLMediaFormat_Key_Bit_RateShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Capture_Rate)
#define MLMediaFormat_Key_Capture_Rate ::LUMIN_MLSDK_API::MLMediaFormat_Key_Capture_RateShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Channel_Count)
#define MLMediaFormat_Key_Channel_Count ::LUMIN_MLSDK_API::MLMediaFormat_Key_Channel_CountShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Channel_Mask)
#define MLMediaFormat_Key_Channel_Mask ::LUMIN_MLSDK_API::MLMediaFormat_Key_Channel_MaskShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Color_Format)
#define MLMediaFormat_Key_Color_Format ::LUMIN_MLSDK_API::MLMediaFormat_Key_Color_FormatShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Duration)
#define MLMediaFormat_Key_Duration ::LUMIN_MLSDK_API::MLMediaFormat_Key_DurationShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_FLAC_Compression_Level)
#define MLMediaFormat_Key_FLAC_Compression_Level ::LUMIN_MLSDK_API::MLMediaFormat_Key_FLAC_Compression_LevelShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Frame_Rate)
#define MLMediaFormat_Key_Frame_Rate ::LUMIN_MLSDK_API::MLMediaFormat_Key_Frame_RateShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Height)
#define MLMediaFormat_Key_Height ::LUMIN_MLSDK_API::MLMediaFormat_Key_HeightShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_I_Frame_Interval)
#define MLMediaFormat_Key_I_Frame_Interval ::LUMIN_MLSDK_API::MLMediaFormat_Key_I_Frame_IntervalShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Intra_Refresh_Period)
#define MLMediaFormat_Key_Intra_Refresh_Period ::LUMIN_MLSDK_API::MLMediaFormat_Key_Intra_Refresh_PeriodShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Is_ADTS)
#define MLMediaFormat_Key_Is_ADTS ::LUMIN_MLSDK_API::MLMediaFormat_Key_Is_ADTSShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Is_Autoselect)
#define MLMediaFormat_Key_Is_Autoselect ::LUMIN_MLSDK_API::MLMediaFormat_Key_Is_AutoselectShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Is_Default)
#define MLMediaFormat_Key_Is_Default ::LUMIN_MLSDK_API::MLMediaFormat_Key_Is_DefaultShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Is_Forced_Subtitle)
#define MLMediaFormat_Key_Is_Forced_Subtitle ::LUMIN_MLSDK_API::MLMediaFormat_Key_Is_Forced_SubtitleShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Language)
#define MLMediaFormat_Key_Language ::LUMIN_MLSDK_API::MLMediaFormat_Key_LanguageShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Max_Height)
#define MLMediaFormat_Key_Max_Height ::LUMIN_MLSDK_API::MLMediaFormat_Key_Max_HeightShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Max_Input_Size)
#define MLMediaFormat_Key_Max_Input_Size ::LUMIN_MLSDK_API::MLMediaFormat_Key_Max_Input_SizeShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Max_Width)
#define MLMediaFormat_Key_Max_Width ::LUMIN_MLSDK_API::MLMediaFormat_Key_Max_WidthShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Mime)
#define MLMediaFormat_Key_Mime ::LUMIN_MLSDK_API::MLMediaFormat_Key_MimeShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_PCM_Encoding)
#define MLMediaFormat_Key_PCM_Encoding ::LUMIN_MLSDK_API::MLMediaFormat_Key_PCM_EncodingShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Push_Blank_Buffers_On_Stop)
#define MLMediaFormat_Key_Push_Blank_Buffers_On_Stop ::LUMIN_MLSDK_API::MLMediaFormat_Key_Push_Blank_Buffers_On_StopShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Repeat_Previous_Frame_After)
#define MLMediaFormat_Key_Repeat_Previous_Frame_After ::LUMIN_MLSDK_API::MLMediaFormat_Key_Repeat_Previous_Frame_AfterShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Sample_Rate)
#define MLMediaFormat_Key_Sample_Rate ::LUMIN_MLSDK_API::MLMediaFormat_Key_Sample_RateShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Stride)
#define MLMediaFormat_Key_Stride ::LUMIN_MLSDK_API::MLMediaFormat_Key_StrideShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Temporal_Layering)
#define MLMediaFormat_Key_Temporal_Layering ::LUMIN_MLSDK_API::MLMediaFormat_Key_Temporal_LayeringShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Width)
#define MLMediaFormat_Key_Width ::LUMIN_MLSDK_API::MLMediaFormat_Key_WidthShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Crop_Left)
#define MLMediaFormat_Key_Crop_Left ::LUMIN_MLSDK_API::MLMediaFormat_Key_Crop_LeftShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Crop_Right)
#define MLMediaFormat_Key_Crop_Right ::LUMIN_MLSDK_API::MLMediaFormat_Key_Crop_RightShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Crop_Bottom)
#define MLMediaFormat_Key_Crop_Bottom ::LUMIN_MLSDK_API::MLMediaFormat_Key_Crop_BottomShim()
CREATE_GLOBAL_SHIM(ml_mediaformat, MLMediaFormatKey, MLMediaFormat_Key_Crop_Top)
#define MLMediaFormat_Key_Crop_Top ::LUMIN_MLSDK_API::MLMediaFormat_Key_Crop_TopShim()

CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatCreateVideo)
#define MLMediaFormatCreateVideo ::LUMIN_MLSDK_API::MLMediaFormatCreateVideoShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatCreateAudio)
#define MLMediaFormatCreateAudio ::LUMIN_MLSDK_API::MLMediaFormatCreateAudioShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatCreateSubtitle)
#define MLMediaFormatCreateSubtitle ::LUMIN_MLSDK_API::MLMediaFormatCreateSubtitleShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatDestroy)
#define MLMediaFormatDestroy ::LUMIN_MLSDK_API::MLMediaFormatDestroyShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatObjectToString)
#define MLMediaFormatObjectToString ::LUMIN_MLSDK_API::MLMediaFormatObjectToStringShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatGetKeyValueInt32)
#define MLMediaFormatGetKeyValueInt32 ::LUMIN_MLSDK_API::MLMediaFormatGetKeyValueInt32Shim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatGetKeyValueInt64)
#define MLMediaFormatGetKeyValueInt64 ::LUMIN_MLSDK_API::MLMediaFormatGetKeyValueInt64Shim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatGetKeyValueFloat)
#define MLMediaFormatGetKeyValueFloat ::LUMIN_MLSDK_API::MLMediaFormatGetKeyValueFloatShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatGetKeySize)
#define MLMediaFormatGetKeySize ::LUMIN_MLSDK_API::MLMediaFormatGetKeySizeShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatGetKeyString)
#define MLMediaFormatGetKeyString ::LUMIN_MLSDK_API::MLMediaFormatGetKeyStringShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatGetKeyByteBuffer)
#define MLMediaFormatGetKeyByteBuffer ::LUMIN_MLSDK_API::MLMediaFormatGetKeyByteBufferShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatKeyByteBufferRelease)
#define MLMediaFormatKeyByteBufferRelease ::LUMIN_MLSDK_API::MLMediaFormatKeyByteBufferReleaseShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatSetKeyInt32)
#define MLMediaFormatSetKeyInt32 ::LUMIN_MLSDK_API::MLMediaFormatSetKeyInt32Shim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatSetKeyInt64)
#define MLMediaFormatSetKeyInt64 ::LUMIN_MLSDK_API::MLMediaFormatSetKeyInt64Shim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatSetKeyFloat)
#define MLMediaFormatSetKeyFloat ::LUMIN_MLSDK_API::MLMediaFormatSetKeyFloatShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatSetKeySize)
#define MLMediaFormatSetKeySize ::LUMIN_MLSDK_API::MLMediaFormatSetKeySizeShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatSetKeyString)
#define MLMediaFormatSetKeyString ::LUMIN_MLSDK_API::MLMediaFormatSetKeyStringShim
CREATE_FUNCTION_SHIM(ml_mediaformat, MLResult, MLMediaFormatSetKeyByteBuffer)
#define MLMediaFormatSetKeyByteBuffer ::LUMIN_MLSDK_API::MLMediaFormatSetKeyByteBufferShim

}

#endif // !defined(WITH_MLSDK) || WITH_MLSDK
