// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#if !defined(WITH_MLSDK) || WITH_MLSDK

#include "Lumin/CAPIShims/LuminAPI.h"

LUMIN_THIRD_PARTY_INCLUDES_START
#include <ml_media_common.h>
#include <ml_media_extractor.h>
LUMIN_THIRD_PARTY_INCLUDES_END

namespace LUMIN_MLSDK_API
{

CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorCreate)
#define MLMediaExtractorCreate ::LUMIN_MLSDK_API::MLMediaExtractorCreateShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorDestroy)
#define MLMediaExtractorDestroy ::LUMIN_MLSDK_API::MLMediaExtractorDestroyShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorSetDataSourceForPath)
#define MLMediaExtractorSetDataSourceForPath ::LUMIN_MLSDK_API::MLMediaExtractorSetDataSourceForPathShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorSetDataSourceForURI)
#define MLMediaExtractorSetDataSourceForURI ::LUMIN_MLSDK_API::MLMediaExtractorSetDataSourceForURIShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorSetDataSourceForURIWithHeaders)
#define MLMediaExtractorSetDataSourceForURIWithHeaders ::LUMIN_MLSDK_API::MLMediaExtractorSetDataSourceForURIWithHeadersShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorSetDataSourceForFD)
#define MLMediaExtractorSetDataSourceForFD ::LUMIN_MLSDK_API::MLMediaExtractorSetDataSourceForFDShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorSetMediaDataSource)
#define MLMediaExtractorSetMediaDataSource ::LUMIN_MLSDK_API::MLMediaExtractorSetMediaDataSourceShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorGetDRMInitData)
#define MLMediaExtractorGetDRMInitData ::LUMIN_MLSDK_API::MLMediaExtractorGetDRMInitDataShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorReleaseDRMInitData)
#define MLMediaExtractorReleaseDRMInitData ::LUMIN_MLSDK_API::MLMediaExtractorReleaseDRMInitDataShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorGetTrackCount)
#define MLMediaExtractorGetTrackCount ::LUMIN_MLSDK_API::MLMediaExtractorGetTrackCountShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorGetTrackFormat)
#define MLMediaExtractorGetTrackFormat ::LUMIN_MLSDK_API::MLMediaExtractorGetTrackFormatShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorSelectTrack)
#define MLMediaExtractorSelectTrack ::LUMIN_MLSDK_API::MLMediaExtractorSelectTrackShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorUnselectTrack)
#define MLMediaExtractorUnselectTrack ::LUMIN_MLSDK_API::MLMediaExtractorUnselectTrackShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorSeekTo)
#define MLMediaExtractorSeekTo ::LUMIN_MLSDK_API::MLMediaExtractorSeekToShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorAdvance)
#define MLMediaExtractorAdvance ::LUMIN_MLSDK_API::MLMediaExtractorAdvanceShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorReadSampleData)
#define MLMediaExtractorReadSampleData ::LUMIN_MLSDK_API::MLMediaExtractorReadSampleDataShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorGetSampleTrackIndex)
#define MLMediaExtractorGetSampleTrackIndex ::LUMIN_MLSDK_API::MLMediaExtractorGetSampleTrackIndexShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorGetSampleTime)
#define MLMediaExtractorGetSampleTime ::LUMIN_MLSDK_API::MLMediaExtractorGetSampleTimeShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorGetSampleFlags)
#define MLMediaExtractorGetSampleFlags ::LUMIN_MLSDK_API::MLMediaExtractorGetSampleFlagsShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorGetSampleCryptoInfo)
#define MLMediaExtractorGetSampleCryptoInfo ::LUMIN_MLSDK_API::MLMediaExtractorGetSampleCryptoInfoShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorReleaseCryptoInfo)
#define MLMediaExtractorReleaseCryptoInfo ::LUMIN_MLSDK_API::MLMediaExtractorReleaseCryptoInfoShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorGetCachedDuration)
#define MLMediaExtractorGetCachedDuration ::LUMIN_MLSDK_API::MLMediaExtractorGetCachedDurationShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorHasCacheReachedEOS)
#define MLMediaExtractorHasCacheReachedEOS ::LUMIN_MLSDK_API::MLMediaExtractorHasCacheReachedEOSShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorGetPSSHInfoCount)
#define MLMediaExtractorGetPSSHInfoCount ::LUMIN_MLSDK_API::MLMediaExtractorGetPSSHInfoCountShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorGetPSSHInfo)
#define MLMediaExtractorGetPSSHInfo ::LUMIN_MLSDK_API::MLMediaExtractorGetPSSHInfoShim
CREATE_FUNCTION_SHIM(ml_mediaextractor, MLResult, MLMediaExtractorReleasePSSHInfo)
#define MLMediaExtractorReleasePSSHInfo ::LUMIN_MLSDK_API::MLMediaExtractorReleasePSSHInfoShim

}

#endif // !defined(WITH_MLSDK) || WITH_MLSDK
