// Copyright Epic Games, Inc. All Rights Reserved.

#include "/Engine/Private/Common.ush"

uint3 GridSize;
RWTexture3D<int>	GridDestinationBuffer;

[numthreads(THREAD_COUNT, THREAD_COUNT, THREAD_COUNT)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
	if ((DispatchThreadId.x < GridSize.x) && (DispatchThreadId.y < GridSize.y) && (DispatchThreadId.z < GridSize.z))
	{
		GridDestinationBuffer[DispatchThreadId] = 0;
	}
}