// Copyright Epic Games, Inc. All Rights Reserved.
#include "MetasoundMathNodes.h"


namespace Metasound
{
	METASOUND_REGISTER_NODE(FAddFloatNode)
	METASOUND_REGISTER_NODE(FAddInt32Node)
	METASOUND_REGISTER_NODE(FAddInt64Node)
	METASOUND_REGISTER_NODE(FAddFrequencyNode)
	METASOUND_REGISTER_NODE(FAddFloatTimeNode)
	METASOUND_REGISTER_NODE(FAddAudioBufferNode)

	METASOUND_REGISTER_NODE(FSubtractFloatNode)
	METASOUND_REGISTER_NODE(FSubtractInt32Node)
	METASOUND_REGISTER_NODE(FSubtractInt64Node)
	METASOUND_REGISTER_NODE(FSubtractFrequencyNode)
	METASOUND_REGISTER_NODE(FSubtractFloatTimeNode)
	METASOUND_REGISTER_NODE(FSubtractAudioBufferNode)

	METASOUND_REGISTER_NODE(FMultiplyFloatNode)
	METASOUND_REGISTER_NODE(FMultiplyInt32Node)
	METASOUND_REGISTER_NODE(FMultiplyInt64Node)
	METASOUND_REGISTER_NODE(FMultiplyFrequencyNode)
	METASOUND_REGISTER_NODE(FMultiplyFloatTimeNode)
	METASOUND_REGISTER_NODE(FMultiplyAudioBufferNode)

	METASOUND_REGISTER_NODE(FDivideFloatNode)
	METASOUND_REGISTER_NODE(FDivideInt32Node)
	METASOUND_REGISTER_NODE(FDivideInt64Node)
	METASOUND_REGISTER_NODE(FDivideFrequencyNode)
	METASOUND_REGISTER_NODE(FDivideFloatTimeNode)

	METASOUND_REGISTER_NODE(FRandRangeFloatNode)
	METASOUND_REGISTER_NODE(FRandRangeInt32Node)
	METASOUND_REGISTER_NODE(FRandRangeInt64Node)
	METASOUND_REGISTER_NODE(FRandRangeFrequencyNode)
	METASOUND_REGISTER_NODE(FRandRangeFloatTimeNode)
}
