// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/UObjectGlobals.h"
#include "UObject/Object.h"

#if WITH_EDITOR
#include "Engine/MeshMerging.h"
#endif

#include "HLODLayer.generated.h"

class UWorldPartition;
class AWorldPartitionHLOD;

UENUM()
enum class EHLODLayerType : uint8
{
	Instancing = 0		UMETA(DisplayName = "Instancing"),
	MeshMerge = 1		UMETA(DisplayName = "Merged Mesh"),
	MeshSimplify = 2	UMETA(DisplayName = "Simplified Mesh")
};

UCLASS(Blueprintable, Config=Engine, PerObjectConfig)
class ENGINE_API UHLODLayer : public UObject
{
	GENERATED_UCLASS_BODY()
	
#if WITH_EDITOR
public:
	static TArray<AWorldPartitionHLOD*> GenerateHLODForCell(UWorldPartition* InWorldPartition, FName InCellName, FBox InCellBounds, float InCellLoadingRange, const TSet<FGuid>& InCellActors);

	static UHLODLayer* GetHLODLayer(const AActor* InActor);
	static bool ShouldIncludeInHLOD(UPrimitiveComponent* InComponent, int32 InLevelIndex);
#endif

#if WITH_EDITORONLY_DATA
	EHLODLayerType GetLayerType() const { return LayerType; }
	const FMeshMergingSettings& GetMeshMergeSettings() const { return MeshMergeSettings; }
	const FMeshProxySettings& GetMeshSimplifySettings() const { return MeshSimplifySettings; }
	const TSoftObjectPtr<UMaterial>& GetHLODMaterial() const { return HLODMaterial; }
	FName GetRuntimeGrid() const { return RuntimeGrid; }
	float GetLoadingRange() const { return LoadingRange; }
#endif

	static bool ShouldIncludeInHLOD(AActor* InActor);

#if WITH_EDITORONLY_DATA
private:
	/** Type of HLOD generation to use */
	UPROPERTY(EditAnywhere, Config, Category=HLOD)
	EHLODLayerType LayerType;

	/** Merged mesh generation settings - Used when this layer is of type EHLODLayerType::MeshMerge */
	UPROPERTY(EditAnywhere, Config, Category=HLOD, meta = (editcondition = "LayerType == EHLODLayerType::MeshMerge"))
	FMeshMergingSettings MeshMergeSettings;

	/** Simplified mesh generation settings - Used when this layer is of type EHLODLayerType::MeshSimplify */
	UPROPERTY(EditAnywhere, Config, Category=HLOD, meta = (editcondition = "LayerType == EHLODLayerType::MeshSimplify"))
	FMeshProxySettings MeshSimplifySettings;

	/** Material that will be used by the generated HLOD static mesh */
	UPROPERTY(EditAnywhere, Config, Category=HLOD, meta = (editcondition = "LayerType == EHLODLayerType::MeshMerge || LayerType == EHLODLayerType::MeshSimplify"))
	TSoftObjectPtr<UMaterial> HLODMaterial;

	/**
	 * Runtime grid that will be used by the generated HLOD. 
	 * For now, this grid will be autogenerated and must not be manually added to the world partition. */
	UPROPERTY(EditAnywhere, Config, Category=HLOD)
	FName RuntimeGrid;

	/** Loading range of the RuntimeGrid */
	UPROPERTY(EditAnywhere, Config, Category=HLOD)
	float LoadingRange;
#endif
};
