// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "UI/VCamConnectionStructs.h"
#include "WidgetConnectionConfig.generated.h"

class UVCamStateSwitcherWidget;
class UVCamWidget;

USTRUCT()
struct VCAMCORE_API FWidgetConnectionConfig
{
	GENERATED_BODY()
	
	/**
	 * Defines the widget whose connections should be updated. Must be a VCamWidget.
	 * This is a reference to a property on the StateSwitcherVCamWidget subclass, intended to have been generated by checking
	 * "Is Variable" in the Designer widget mode.
	 */
	UPROPERTY(EditAnywhere, Category = "Connection")
	FName Widget = NAME_None;
	
	/**
	 * Key: A valid key of in UVCamWidget::Connections of the widget identified via WidgetProperty.
	 * Value: The settings to use for this connection.
	 */
	UPROPERTY(EditAnywhere, Category = "Connection")
	TMap<FName, FVCamConnectionTargetSettings> ConnectionTargets;

	UVCamWidget* ResolveWidget(UVCamStateSwitcherWidget* OwnerWidget) const;
	bool HasNoWidgetSet() const { return Widget == NAME_None; }
};