// Copyright 1998-2019 Epic Games, Inc. All Rights Reserved.
#pragma once

#include "UObject/Object.h"
#include "MovieRenderPipelineDataTypes.h"
#include "Engine/EngineTypes.h"
#include "MoviePipelineSetting.h"
#include "MoviePipelineOutputBase.generated.h"

class UMoviePipeline;

/**
* A base class for different output containers for the data generated by the Movie Pipeline,
* i.e: image sequences, video containers, etc.
*/
UCLASS(Blueprintable, Abstract)
class MOVIERENDERPIPELINECORE_API UMoviePipelineOutputBase : public UMoviePipelineSetting
{
	GENERATED_BODY()
public:

	/** 
	* Called once when all frames have been produced for the pipeline. Use this as an indicator to start flushing to disk. 
	* Async processes can be started here and HasFinishedProcessing() will be called each frame until all all containers
	* return true, at which point Finalize will be called.
	*/
	void BeginFinalize() { BeginFinalizeImpl(); }

	/**
	* Called each frame to check to see if this output container has finished processing. Finalize won't be called until
	* all output containers return true for this. 
	*/
	bool HasFinishedProcessing() { return HasFinishedProcessingImpl(); }

	/** 
	* Called after all output containers have reported that they are done processing.
	*/
	void Finalize() { FinalizeImpl(); }

	/**
	* This is called when a new shot starts, before warm up happens. See OnFrameProductionStart.
	*/
	void OnShotInitialized(const TOptional<FMoviePipelineShotInfo> PrevShot, const FMoviePipelineShotInfo& NewShot) { OnShotInitializedImpl(PrevShot, NewShot); }
	
	/**
	* This is called when a shot ends, right after the last frame is rendered.
	*/
	void OnShotFinished(const FMoviePipelineShotInfo& Shot) { OnShotFinishedImpl(Shot); }

	/**
	* This is called during the Shutdown process of the Pipeline. This is after finalization.
	*/
	void OnPipelineFinished() { OnPipelineFinishedImpl(); }

	/**
	* Called at the end of the frame, before rendering has happened for that frame.
	*/
	void OnPostTick() { OnPostTickImpl(); }

	virtual void OnRecieveImageDataImpl(FMoviePipelineMergerOutputFrame* InMergedOutputFrame) {}

protected:
	virtual bool IsValidOnShots() const override { return false; }
	virtual bool IsValidOnMaster() const override { return true; }
protected:
	virtual void OnShotInitializedImpl(const TOptional<FMoviePipelineShotInfo> PrevShot, const FMoviePipelineShotInfo& NewShot) {}
	virtual void OnShotFinishedImpl(const FMoviePipelineShotInfo& Shot) {}

	virtual void FinalizeImpl() {}
	virtual void BeginFinalizeImpl() {}
	virtual bool HasFinishedProcessingImpl() { return true; }
	virtual void OnPipelineFinishedImpl() {}
	virtual void OnPostTickImpl() {}
};