// Copyright Epic Games, Inc. All Rights Reserved.

//#pragma once

#include "ShaderParameterUtils.h"
#include "RenderGraphUtils.h"

// HLSL runtime and DirectML runtime use different shader parameter access patterns
#ifdef NNXRT_RDG_DML
#define NNXRT_RDG_BUFFER_SRV(View, BufferName) RDG_BUFFER_ACCESS(BufferName, ERHIAccess::UAVCompute)
#define NNXRT_RDG_BUFFER_UAV(View, BufferName) RDG_BUFFER_ACCESS(BufferName, ERHIAccess::UAVCompute)
#else
#define NNXRT_RDG_BUFFER_SRV(View, BufferName) SHADER_PARAMETER_RDG_BUFFER_SRV(View, BufferName)
#define NNXRT_RDG_BUFFER_UAV(View, BufferName) SHADER_PARAMETER_RDG_BUFFER_UAV(View, BufferName)
#endif

#ifdef NNXRT_RDG_DML
#define NNXRT_BEGIN_SHADER_PARAMETER_STRUCT(Name) BEGIN_SHADER_PARAMETER_STRUCT(Name, )
#else
#define NNXRT_BEGIN_SHADER_PARAMETER_STRUCT(Name) BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
#endif

#define NNXRT_END_SHADER_PARAMETER_STRUCT END_SHADER_PARAMETER_STRUCT

//Unary element wise operators
#define NNXRT_ELEMENTWISEUNARY_PARAMETER_STRUCT() \
	NNXRT_BEGIN_SHADER_PARAMETER_STRUCT(FMLElementWiseUnaryParameters) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, Input) \
		NNXRT_RDG_BUFFER_UAV(RWBuffer<float>, Output) \
		SHADER_PARAMETER(uint32, Num) \
		SHADER_PARAMETER(uint32, ThreadCountX) \
		SHADER_PARAMETER(float, Alpha) \
		SHADER_PARAMETER(float, Beta) \
		SHADER_PARAMETER(float, Gamma) \
	NNXRT_END_SHADER_PARAMETER_STRUCT()

#ifdef NNXRT_RDG_DML
NNXRT_ELEMENTWISEUNARY_PARAMETER_STRUCT()
#endif

//Variadic element wise operators
#define NNXRT_ELEMENTWISEVARIADIC_PARAMETER_STRUCT() \
	NNXRT_BEGIN_SHADER_PARAMETER_STRUCT(FMLElementWiseVariadicParameters) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, Input0) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, Input1) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, Input2) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, Input3) \
		NNXRT_RDG_BUFFER_UAV(RWBuffer<float>, Output) \
		SHADER_PARAMETER(FUint32Vector4, Input0Info0) \
		SHADER_PARAMETER(FUint32Vector4, Input0Info1) \
		SHADER_PARAMETER(FUint32Vector4, Input1Info0) \
		SHADER_PARAMETER(FUint32Vector4, Input1Info1) \
		SHADER_PARAMETER(FUint32Vector4, Input2Info0) \
		SHADER_PARAMETER(FUint32Vector4, Input2Info1) \
		SHADER_PARAMETER(FUint32Vector4, Input3Info0) \
		SHADER_PARAMETER(FUint32Vector4, Input3Info1) \
		SHADER_PARAMETER(FUint32Vector4, OutInfo0) \
		SHADER_PARAMETER(FUint32Vector4, OutInfo1) \
		SHADER_PARAMETER(uint32, OutRank) \
		SHADER_PARAMETER(uint32, Num) \
		SHADER_PARAMETER(uint32, ThreadCountX) \
		SHADER_PARAMETER(float, Scale) \
	NNXRT_END_SHADER_PARAMETER_STRUCT()

#ifdef NNXRT_RDG_DML
NNXRT_ELEMENTWISEVARIADIC_PARAMETER_STRUCT()
#endif

//Binary element wise operators
#define NNXRT_ELEMENTWISEBINARY_PARAMETER_STRUCT() \
	NNXRT_BEGIN_SHADER_PARAMETER_STRUCT(FMLElementWiseBinaryParameters) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, LHSInput) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, RHSInput) \
		NNXRT_RDG_BUFFER_UAV(RWBuffer<float>, Output) \
		SHADER_PARAMETER(FUint32Vector4, LHSInfo0) \
		SHADER_PARAMETER(FUint32Vector4, LHSInfo1) \
		SHADER_PARAMETER(FUint32Vector4, RHSInfo0) \
		SHADER_PARAMETER(FUint32Vector4, RHSInfo1) \
		SHADER_PARAMETER(FUint32Vector4, OutInfo0) \
		SHADER_PARAMETER(FUint32Vector4, OutInfo1) \
		SHADER_PARAMETER(uint32, OutRank) \
		SHADER_PARAMETER(uint32, Num) \
		SHADER_PARAMETER(uint32, ThreadCountX) \
	NNXRT_END_SHADER_PARAMETER_STRUCT()

#ifdef NNXRT_RDG_DML
NNXRT_ELEMENTWISEBINARY_PARAMETER_STRUCT()
#endif

//Gemm
#define NNXRT_GEMM_MAX_NUM_STACK_DIMENSIONS 8

#define NNXRT_GEMM_PARAMETER_STRUCT() \
	NNXRT_BEGIN_SHADER_PARAMETER_STRUCT(FMLGemmParameters) \
		SHADER_PARAMETER(float, Alpha) \
		SHADER_PARAMETER(float, Beta) \
		SHADER_PARAMETER(int32, TransA) \
		SHADER_PARAMETER(int32, TransB) \
		SHADER_PARAMETER(uint32, M) \
		SHADER_PARAMETER(uint32, N) \
		SHADER_PARAMETER(uint32, K) \
		SHADER_PARAMETER(uint32, MxK) \
		SHADER_PARAMETER(uint32, KxN) \
		SHADER_PARAMETER(uint32, MxN) \
		SHADER_PARAMETER(uint32, CWidth) \
		SHADER_PARAMETER(uint32, CHeight) \
		SHADER_PARAMETER(float, CScalar) \
		SHADER_PARAMETER_ARRAY(FUint32Vector4, StackShapeA_StackShapeB_StackStrideA_StackStrideB, [NNXRT_GEMM_MAX_NUM_STACK_DIMENSIONS]) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, A) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, B) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, C) \
		NNXRT_RDG_BUFFER_UAV(RWBuffer<float>, Y) \
	NNXRT_END_SHADER_PARAMETER_STRUCT()

#ifdef NNXRT_RDG_DML
NNXRT_GEMM_PARAMETER_STRUCT()
#endif

//Conv
#define NNXRT_CONV_MAX_NUM_DIMENSIONS 4

#define NNXRT_CONV_PARAMETER_STRUCT() \
	NNXRT_BEGIN_SHADER_PARAMETER_STRUCT(FMLConvParameters) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, X) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, W) \
		NNXRT_RDG_BUFFER_UAV(RWBuffer<float>, Y) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, B) \
		SHADER_PARAMETER_ARRAY(FIntVector4, Dilation_Stride_XBlockStartOffset_DilationXBlockStride, [NNXRT_CONV_MAX_NUM_DIMENSIONS]) \
		SHADER_PARAMETER_ARRAY(FIntVector4, GroupStride_GroupShape_GroupThreadStride_StrideXBlockStride, [NNXRT_CONV_MAX_NUM_DIMENSIONS]) \
		SHADER_PARAMETER_ARRAY(FIntVector4, YDimension_YMemoryStride_XDimension_XMemoryStride, [NNXRT_CONV_MAX_NUM_DIMENSIONS]) \
		SHADER_PARAMETER_ARRAY(FIntVector4, XBlockStartStride_XBlockStride_WDimension_WDimensionDilationXBlockStride, [NNXRT_CONV_MAX_NUM_DIMENSIONS]) \
		SHADER_PARAMETER_ARRAY(FVector4f, OneDiv_GroupStride_GroupThreadStride_XBlockStride, [NNXRT_CONV_MAX_NUM_DIMENSIONS]) \
		SHADER_PARAMETER(int32, NumWChannels) \
		SHADER_PARAMETER(int32, YBatchStride) \
		SHADER_PARAMETER(int32, YOutputKernelStride) \
		SHADER_PARAMETER(int32, XBatchStride) \
		SHADER_PARAMETER(int32, XChannelStride) \
		SHADER_PARAMETER(int32, XBlockSize) \
		SHADER_PARAMETER(int32, NumChannelBatches) \
		SHADER_PARAMETER(int32, NumChannelsPerBatch) \
		SHADER_PARAMETER(int32, WOutputKernelStride) \
		SHADER_PARAMETER(int32, WChannelBatchSize) \
		SHADER_PARAMETER(int32, WChannelSize) \
		SHADER_PARAMETER(float, GroupsDivM) \
	NNXRT_END_SHADER_PARAMETER_STRUCT()

#ifdef NNXRT_RDG_DML
NNXRT_CONV_PARAMETER_STRUCT()
#endif

//ConvTranspose
#define NNXRT_CONVTRANSPOSE_MAX_NUM_STACK_DIMENSIONS 4
#define NNXRT_CONVTRANSPOSE_MIN_NUM_READS_PER_THREAD_POW2 1
#define NNXRT_CONVTRANSPOSE_MIN_NUM_READS_PER_THREAD_POW2 3

#define NNXRT_CONVTRANSPOSE_PARAMETER_STRUCT() \
	NNXRT_BEGIN_SHADER_PARAMETER_STRUCT(FMLConvParameters) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, X) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, W) \
		NNXRT_RDG_BUFFER_UAV(RWBuffer<float>, Y) \
		NNXRT_RDG_BUFFER_SRV(Buffer<float>, B) \
		SHADER_PARAMETER_ARRAY(FIntVector4, Dilation_Stride_XBlockStartOffset_DilationXBlockStride, [NNXRT_CONVTRANSPOSE_MAX_NUM_STACK_DIMENSIONS]) \
		SHADER_PARAMETER_ARRAY(FIntVector4, GroupStride_GroupShape_GroupThreadStride_StrideXBlockStride, [:NNXRT_CONVTRANSPOSE_MAX_NUM_STACK_DIMENSIONS])\
		SHADER_PARAMETER_ARRAY(FIntVector4, YDimension_YMemoryStride_XDimension_XMemoryStride, NNXRT_CONVTRANSPOSE_MAX_NUM_STACK_DIMENSIONS])\
		SHADER_PARAMETER_ARRAY(FIntVector4, XBlockStartStride_XBlockStride_WDimension_WDimensionDilationXBlockStride, [NNXRT_CONVTRANSPOSE_MAX_NUM_STACK_DIMENSIONS])\
		SHADER_PARAMETER_ARRAY(FVector4f, OneDiv_GroupStride_GroupThreadStride_OneDivStride, [NNXRT_CONVTRANSPOSE_MAX_NUM_STACK_DIMENSIONS])\
		SHADER_PARAMETER(int32, NumWChannels)\
		SHADER_PARAMETER(int32, NumOutChannelsDivGroup)\
		SHADER_PARAMETER(int32, YBatchStride)\
		SHADER_PARAMETER(int32, YOutputKernelStride)\
		SHADER_PARAMETER(int32, XBatchStride)\
		SHADER_PARAMETER(int32, XChannelStride)\
		SHADER_PARAMETER(int32, XBlockSize)\
		SHADER_PARAMETER(int32, NumChannelBatches)\
		SHADER_PARAMETER(int32, NumChannelsPerBatch)\
		SHADER_PARAMETER(int32, WOutputKernelStride)\
		SHADER_PARAMETER(int32, WChannelBatchSize)\
		SHADER_PARAMETER(int32, WChannelSize)\
		SHADER_PARAMETER(float, GroupsDivM)\
		SHADER_PARAMETER(float, OneDivGroup)\
	NNXRT_END_SHADER_PARAMETER_STRUCT()

#ifdef NNXRT_RDG_DML
NNXRT_CONVTRANSPOSE_PARAMETER_STRUCT()
#endif