// Copyright 1998-2019 Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "RigVMMemory.h"

typedef TArrayView<void*> FRigVMUserDataArray;
typedef void (*FRigVMFunctionPtr)(const FRigVMOperandArray&, FRigVMMemoryContainerPtrArray&, const FRigVMUserDataArray&);

/**
 * The FRigVMFunction is used to represent a function pointer generated by UHT 
 * for a given name. The name might be something like "FMyStruct::MyVirtualMethod"
 */
struct RIGVM_API FRigVMFunction
{
	const TCHAR* Name;
	FRigVMFunctionPtr FunctionPtr;

	FRigVMFunction()
		: Name(nullptr)
		, FunctionPtr(nullptr)
	{
	}

	FRigVMFunction(const TCHAR* InName, FRigVMFunctionPtr InFunctionPtr)
		: Name(InName)
		, FunctionPtr(InFunctionPtr)
	{
	}
};

/**
 * The FRigVMRegistry is used to manage all known function pointers
 * for use in the RigVM. The Register method is called automatically
 * when the static struct is initially constructed for each USTRUCT
 * hosting a RIGVM_METHOD enabled virtual function.
 */
struct RIGVM_API FRigVMRegistry
{
public:

	// Returns the singleton registry
	static FRigVMRegistry& Get();

	// Registers a function given its name.
	// The name will be the name of the struct and virtual method,
	// for example "FMyStruct::MyVirtualMethod"
	void Register(const TCHAR* InName, FRigVMFunctionPtr InFunctionPtr);

	// Refreshes the list and finds the function pointers
	// based on the names.
	void Refresh();

	// Returns a function pointer given its name
	FRigVMFunctionPtr Find(const TCHAR* InName) const;

private:

	// disable default constructor
	FRigVMRegistry() {}
	// disable copy constructor
	FRigVMRegistry(const FRigVMRegistry&) = delete;
	// disable assignment operator
	FRigVMRegistry& operator= (const FRigVMRegistry &InOther) = delete;

	// memory for all functions
	TArray<FRigVMFunction> Functions;

	static FRigVMRegistry s_RigVMRegistry;
};
