// David Eberly, Geometric Tools, Redmond WA 98052
// Copyright (c) 1998-2019
// Distributed under the Boost Software License, Version 1.0.
// http://www.boost.org/LICENSE_1_0.txt
// http://www.geometrictools.com/License/Boost/LICENSE_1_0.txt
// File Version: 3.0.29 (2019/02/13)

#pragma once

// I used to have these sections ordered alphabetically by the names in
// the comments.  Two phase name lookups for template matching by the
// MSVS 2017 compiler had no problems with the ordering, but the Linux
// g++ compiler does.  This occurred when trying to match std::sqrt(...)
// and other math functions when the inputs are based on BSNumber or
// BSRational.  The "Arithmetic" section has been moved before all other
// headers, and the UInteger* files have been moved before the BS* files.

// Arithmetic
#include <GTEngine/Mathematics/GteBitHacks.h>
#include <GTEngine/Mathematics/GteIEEEBinary.h>
#include <GTEngine/Mathematics/GteIEEEBinary16.h>
#include <GTEngine/Mathematics/GteMath.h>
#include <GTEngine/Mathematics/GteArbitraryPrecision.h>
#include <GTEngine/Mathematics/GteQuadraticField.h>

// Algebra
#include <GTEngine/Mathematics/GteAxisAngle.h>
#include <GTEngine/Mathematics/GteBandedMatrix.h>
#include <GTEngine/Mathematics/GteConvertCoordinates.h>
#include <GTEngine/Mathematics/GteEulerAngles.h>
#include <GTEngine/Mathematics/GteGMatrix.h>
#include <GTEngine/Mathematics/GteGVector.h>
#include <GTEngine/Mathematics/GteMatrix.h>
#include <GTEngine/Mathematics/GteMatrix2x2.h>
#include <GTEngine/Mathematics/GteMatrix3x3.h>
#include <GTEngine/Mathematics/GteMatrix4x4.h>
#include <GTEngine/Mathematics/GtePolynomial1.h>
#include <GTEngine/Mathematics/GteQuaternion.h>
#include <GTEngine/Mathematics/GteRotation.h>
#include <GTEngine/Mathematics/GteVector.h>
#include <GTEngine/Mathematics/GteVector2.h>
#include <GTEngine/Mathematics/GteVector3.h>
#include <GTEngine/Mathematics/GteVector4.h>

// Approximation
#include <GTEngine/Mathematics/GteApprCircle2.h>
#include <GTEngine/Mathematics/GteApprCone3.h>
#include <GTEngine/Mathematics/GteApprCylinder3.h>
#include <GTEngine/Mathematics/GteApprEllipseByArcs.h>
#include <GTEngine/Mathematics/GteApprEllipse2.h>
#include <GTEngine/Mathematics/GteApprEllipsoid3.h>
#include <GTEngine/Mathematics/GteApprGaussian2.h>
#include <GTEngine/Mathematics/GteApprGaussian3.h>
#include <GTEngine/Mathematics/GteApprGreatCircle3.h>
#include <GTEngine/Mathematics/GteApprHeightLine2.h>
#include <GTEngine/Mathematics/GteApprHeightPlane3.h>
#include <GTEngine/Mathematics/GteApprOrthogonalLine2.h>
#include <GTEngine/Mathematics/GteApprOrthogonalLine3.h>
#include <GTEngine/Mathematics/GteApprOrthogonalPlane3.h>
#include <GTEngine/Mathematics/GteApprParaboloid3.h>
#include <GTEngine/Mathematics/GteApprPolynomial2.h>
#include <GTEngine/Mathematics/GteApprPolynomial3.h>
#include <GTEngine/Mathematics/GteApprPolynomial4.h>
#include <GTEngine/Mathematics/GteApprPolynomialSpecial2.h>
#include <GTEngine/Mathematics/GteApprPolynomialSpecial3.h>
#include <GTEngine/Mathematics/GteApprPolynomialSpecial4.h>
#include <GTEngine/Mathematics/GteApprQuadratic2.h>
#include <GTEngine/Mathematics/GteApprQuadratic3.h>
#include <GTEngine/Mathematics/GteApprQuery.h>
#include <GTEngine/Mathematics/GteApprSphere3.h>
#include <GTEngine/Mathematics/GteApprTorus3.h>

// ComputationalGeometry
#include <GTEngine/Mathematics/GteConstrainedDelaunay2.h>
#include <GTEngine/Mathematics/GteConvexHull2.h>
#include <GTEngine/Mathematics/GteConvexHull3.h>
#include <GTEngine/Mathematics/GteDelaunay2.h>
#include <GTEngine/Mathematics/GteDelaunay2Mesh.h>
#include <GTEngine/Mathematics/GteDelaunay3.h>
#include <GTEngine/Mathematics/GteDelaunay3Mesh.h>
#include <GTEngine/Mathematics/GteEdgeKey.h>
#include <GTEngine/Mathematics/GteETManifoldMesh.h>
#include <GTEngine/Mathematics/GteETNonmanifoldMesh.h>
#include <GTEngine/Mathematics/GteFeatureKey.h>
#include <GTEngine/Mathematics/GteGenerateMeshUV.h>
#include <GTEngine/Mathematics/GteIsPlanarGraph.h>
#include <GTEngine/Mathematics/GteMinimalCycleBasis.h>
#include <GTEngine/Mathematics/GteMinimumAreaBox2.h>
#include <GTEngine/Mathematics/GteMinimumAreaCircle2.h>
#include <GTEngine/Mathematics/GteMinimumVolumeBox3.h>
#include <GTEngine/Mathematics/GteMinimumVolumeSphere3.h>
#include <GTEngine/Mathematics/GteNearestNeighborQuery.h>
#include <GTEngine/Mathematics/GteOBBTreeOfPoints.h>
#include <GTEngine/Mathematics/GtePlanarMesh.h>
#include <GTEngine/Mathematics/GtePrimalQuery2.h>
#include <GTEngine/Mathematics/GtePrimalQuery3.h>
#include <GTEngine/Mathematics/GteSeparatePoints2.h>
#include <GTEngine/Mathematics/GteSeparatePoints3.h>
#include <GTEngine/Mathematics/GteTetrahedronKey.h>
#include <GTEngine/Mathematics/GteTriangleKey.h>
#include <GTEngine/Mathematics/GteTriangulateCDT.h>
#include <GTEngine/Mathematics/GteTriangulateEC.h>
#include <GTEngine/Mathematics/GteTSManifoldMesh.h>
#include <GTEngine/Mathematics/GteUniqueVerticesTriangles.h>
#include <GTEngine/Mathematics/GteVEManifoldMesh.h>
#include <GTEngine/Mathematics/GteVETManifoldMesh.h>
#include <GTEngine/Mathematics/GteVETNonmanifoldMesh.h>
#include <GTEngine/Mathematics/GteVertexCollapseMesh.h>

// Containment
#include <GTEngine/Mathematics/GteContAlignedBox.h>
#include <GTEngine/Mathematics/GteContCapsule3.h>
#include <GTEngine/Mathematics/GteContCircle2.h>
#include <GTEngine/Mathematics/GteContCone.h>
#include <GTEngine/Mathematics/GteContCylinder3.h>
#include <GTEngine/Mathematics/GteContEllipse2.h>
#include <GTEngine/Mathematics/GteContEllipse2MinCR.h>
#include <GTEngine/Mathematics/GteContEllipsoid3.h>
#include <GTEngine/Mathematics/GteContEllipsoid3MinCR.h>
#include <GTEngine/Mathematics/GteContOrientedBox2.h>
#include <GTEngine/Mathematics/GteContOrientedBox3.h>
#include <GTEngine/Mathematics/GteContPointInPolygon2.h>
#include <GTEngine/Mathematics/GteContPointInPolyhedron3.h>
#include <GTEngine/Mathematics/GteContScribeCircle2.h>
#include <GTEngine/Mathematics/GteContScribeCircle3Sphere3.h>
#include <GTEngine/Mathematics/GteContSphere3.h>

// CurvesSurfacesVolumes
#include <GTEngine/Mathematics/GteBasisFunction.h>
#include <GTEngine/Mathematics/GteBezierCurve.h>
#include <GTEngine/Mathematics/GteBSplineCurve.h>
#include <GTEngine/Mathematics/GteBSplineCurveFit.h>
#include <GTEngine/Mathematics/GteBSplineSurface.h>
#include <GTEngine/Mathematics/GteBSplineSurfaceFit.h>
#include <GTEngine/Mathematics/GteBSplineVolume.h>
#include <GTEngine/Mathematics/GteDarbouxFrame.h>
#include <GTEngine/Mathematics/GteFrenetFrame.h>
#include <GTEngine/Mathematics/GteIndexAttribute.h>
#include <GTEngine/Mathematics/GteMesh.h>
#include <GTEngine/Mathematics/GteNaturalSplineCurve.h>
#include <GTEngine/Mathematics/GteNURBSCircle.h>
#include <GTEngine/Mathematics/GteNURBSCurve.h>
#include <GTEngine/Mathematics/GteNURBSSurface.h>
#include <GTEngine/Mathematics/GteNURBSSphere.h>
#include <GTEngine/Mathematics/GteNURBSVolume.h>
#include <GTEngine/Mathematics/GteParametricCurve.h>
#include <GTEngine/Mathematics/GteParametricSurface.h>
#include <GTEngine/Mathematics/GteRectangleMesh.h>
#include <GTEngine/Mathematics/GteRectanglePatchMesh.h>
#include <GTEngine/Mathematics/GteRevolutionMesh.h>
#include <GTEngine/Mathematics/GteTCBSplineCurve.h>
#include <GTEngine/Mathematics/GteTubeMesh.h>
#include <GTEngine/Mathematics/GteVertexAttribute.h>

// Distance
#include <GTEngine/Mathematics/GteDCPQuery.h>
#include <GTEngine/Mathematics/GteDistAlignedBoxAlignedBox.h>
#include <GTEngine/Mathematics/GteDistAlignedBox3OrientedBox3.h>
#include <GTEngine/Mathematics/GteDistCircle3Circle3.h>
#include <GTEngine/Mathematics/GteDistLine3AlignedBox3.h>
#include <GTEngine/Mathematics/GteDistLine3Circle3.h>
#include <GTEngine/Mathematics/GteDistLine3OrientedBox3.h>
#include <GTEngine/Mathematics/GteDistLine3Rectangle3.h>
#include <GTEngine/Mathematics/GteDistLine3Triangle3.h>
#include <GTEngine/Mathematics/GteDistLineLine.h>
#include <GTEngine/Mathematics/GteDistLineRay.h>
#include <GTEngine/Mathematics/GteDistLineSegment.h>
#include <GTEngine/Mathematics/GteDistOrientedBox3OrientedBox3.h>
#include <GTEngine/Mathematics/GteDistPoint3Circle3.h>
#include <GTEngine/Mathematics/GteDistPoint3ConvexPolyhedron3.h>
#include <GTEngine/Mathematics/GteDistPoint3Cylinder3.h>
#include <GTEngine/Mathematics/GteDistPoint3Frustum3.h>
#include <GTEngine/Mathematics/GteDistPoint3Plane3.h>
#include <GTEngine/Mathematics/GteDistPoint3Rectangle3.h>
#include <GTEngine/Mathematics/GteDistPoint3Tetrahedron3.h>
#include <GTEngine/Mathematics/GteDistPointAlignedBox.h>
#include <GTEngine/Mathematics/GteDistPointHyperellipsoid.h>
#include <GTEngine/Mathematics/GteDistPointLine.h>
#include <GTEngine/Mathematics/GteDistPointOrientedBox.h>
#include <GTEngine/Mathematics/GteDistPointRay.h>
#include <GTEngine/Mathematics/GteDistPointSegment.h>
#include <GTEngine/Mathematics/GteDistPointTriangle.h>
#include <GTEngine/Mathematics/GteDistPointTriangleExact.h>
#include <GTEngine/Mathematics/GteDistRay3AlignedBox3.h>
#include <GTEngine/Mathematics/GteDistRay3OrientedBox3.h>
#include <GTEngine/Mathematics/GteDistRay3Rectangle3.h>
#include <GTEngine/Mathematics/GteDistRay3Triangle3.h>
#include <GTEngine/Mathematics/GteDistRayRay.h>
#include <GTEngine/Mathematics/GteDistRaySegment.h>
#include <GTEngine/Mathematics/GteDistRectangle3Rectangle3.h>
#include <GTEngine/Mathematics/GteDistRectangle3AlignedBox3.h>
#include <GTEngine/Mathematics/GteDistRectangle3OrientedBox3.h>
#include <GTEngine/Mathematics/GteDistSegment3AlignedBox3.h>
#include <GTEngine/Mathematics/GteDistSegment3OrientedBox3.h>
#include <GTEngine/Mathematics/GteDistSegment3Rectangle3.h>
#include <GTEngine/Mathematics/GteDistSegment3Triangle3.h>
#include <GTEngine/Mathematics/GteDistSegmentSegment.h>
#include <GTEngine/Mathematics/GteDistSegmentSegmentExact.h>
#include <GTEngine/Mathematics/GteDistTriangle3AlignedBox3.h>
#include <GTEngine/Mathematics/GteDistTriangle3OrientedBox3.h>
#include <GTEngine/Mathematics/GteDistTriangle3Rectangle3.h>
#include <GTEngine/Mathematics/GteDistTriangle3Triangle3.h>

// Functions
#include <GTEngine/Mathematics/GteACosEstimate.h>
#include <GTEngine/Mathematics/GteASinEstimate.h>
#include <GTEngine/Mathematics/GteATanEstimate.h>
#include <GTEngine/Mathematics/GteChebyshevRatio.h>
#include <GTEngine/Mathematics/GteCosEstimate.h>
#include <GTEngine/Mathematics/GteExp2Estimate.h>
#include <GTEngine/Mathematics/GteExpEstimate.h>
#include <GTEngine/Mathematics/GteInvSqrtEstimate.h>
#include <GTEngine/Mathematics/GteLog2Estimate.h>
#include <GTEngine/Mathematics/GteLogEstimate.h>
#include <GTEngine/Mathematics/GteSinEstimate.h>
#include <GTEngine/Mathematics/GteSlerpEstimate.h>
#include <GTEngine/Mathematics/GteSqrtEstimate.h>
#include <GTEngine/Mathematics/GteTanEstimate.h>

// GeometricPrimitives
#include <GTEngine/Mathematics/GteAlignedBox.h>
#include <GTEngine/Mathematics/GteArc2.h>
#include <GTEngine/Mathematics/GteCapsule.h>
#include <GTEngine/Mathematics/GteCircle3.h>
#include <GTEngine/Mathematics/GteCone.h>
#include <GTEngine/Mathematics/GteConvexPolyhedron3.h>
#include <GTEngine/Mathematics/GteCylinder3.h>
#include <GTEngine/Mathematics/GteEllipse3.h>
#include <GTEngine/Mathematics/GteFrustum3.h>
#include <GTEngine/Mathematics/GteHalfspace.h>
#include <GTEngine/Mathematics/GteHyperellipsoid.h>
#include <GTEngine/Mathematics/GteHyperplane.h>
#include <GTEngine/Mathematics/GteHypersphere.h>
#include <GTEngine/Mathematics/GteLine.h>
#include <GTEngine/Mathematics/GteOrientedBox.h>
#include <GTEngine/Mathematics/GtePolygon2.h>
#include <GTEngine/Mathematics/GtePolyhedron3.h>
#include <GTEngine/Mathematics/GteRay.h>
#include <GTEngine/Mathematics/GteRectangle.h>
#include <GTEngine/Mathematics/GteSector2.h>
#include <GTEngine/Mathematics/GteSegment.h>
#include <GTEngine/Mathematics/GteTetrahedron3.h>
#include <GTEngine/Mathematics/GteTorus3.h>
#include <GTEngine/Mathematics/GteTriangle.h>

// Interpolation
#include <GTEngine/Mathematics/GteIntpAkima1.h>
#include <GTEngine/Mathematics/GteIntpAkimaNonuniform1.h>
#include <GTEngine/Mathematics/GteIntpAkimaUniform1.h>
#include <GTEngine/Mathematics/GteIntpAkimaUniform2.h>
#include <GTEngine/Mathematics/GteIntpAkimaUniform3.h>
#include <GTEngine/Mathematics/GteIntpBicubic2.h>
#include <GTEngine/Mathematics/GteIntpBilinear2.h>
#include <GTEngine/Mathematics/GteIntpBSplineUniform.h>
#include <GTEngine/Mathematics/GteIntpLinearNonuniform2.h>
#include <GTEngine/Mathematics/GteIntpLinearNonuniform3.h>
#include <GTEngine/Mathematics/GteIntpQuadraticNonuniform2.h>
#include <GTEngine/Mathematics/GteIntpSphere2.h>
#include <GTEngine/Mathematics/GteIntpThinPlateSpline2.h>
#include <GTEngine/Mathematics/GteIntpThinPlateSpline3.h>
#include <GTEngine/Mathematics/GteIntpTricubic3.h>
#include <GTEngine/Mathematics/GteIntpTrilinear3.h>
#include <GTEngine/Mathematics/GteIntpVectorField2.h>

// Intersection
#include <GTEngine/Mathematics/GteFIQuery.h>
#include <GTEngine/Mathematics/GteIntrAlignedBox2AlignedBox2.h>
#include <GTEngine/Mathematics/GteIntrAlignedBox2Circle2.h>
#include <GTEngine/Mathematics/GteIntrAlignedBox2OrientedBox2.h>
#include <GTEngine/Mathematics/GteIntrAlignedBox3AlignedBox3.h>
#include <GTEngine/Mathematics/GteIntrAlignedBox3Cone3.h>
#include <GTEngine/Mathematics/GteIntrAlignedBox3Cylinder3.h>
#include <GTEngine/Mathematics/GteIntrAlignedBox3OrientedBox3.h>
#include <GTEngine/Mathematics/GteIntrAlignedBox3Sphere3.h>
#include <GTEngine/Mathematics/GteIntrArc2Arc2.h>
#include <GTEngine/Mathematics/GteIntrCapsule3Capsule3.h>
#include <GTEngine/Mathematics/GteIntrCircle2Arc2.h>
#include <GTEngine/Mathematics/GteIntrCircle2Circle2.h>
#include <GTEngine/Mathematics/GteIntrConvexPolygonHyperplane.h>
#include <GTEngine/Mathematics/GteIntrDisk2Sector2.h>
#include <GTEngine/Mathematics/GteIntrEllipse2Ellipse2.h>
#include <GTEngine/Mathematics/GteIntrEllipsoid3Ellipsoid3.h>
#include <GTEngine/Mathematics/GteIntrHalfspace2Polygon2.h>
#include <GTEngine/Mathematics/GteIntrHalfspace3Capsule3.h>
#include <GTEngine/Mathematics/GteIntrHalfspace3Cylinder3.h>
#include <GTEngine/Mathematics/GteIntrHalfspace3Ellipsoid3.h>
#include <GTEngine/Mathematics/GteIntrHalfspace3OrientedBox3.h>
#include <GTEngine/Mathematics/GteIntrHalfspace3Segment3.h>
#include <GTEngine/Mathematics/GteIntrHalfspace3Sphere3.h>
#include <GTEngine/Mathematics/GteIntrHalfspace3Triangle3.h>
#include <GTEngine/Mathematics/GteIntrIntervals.h>
#include <GTEngine/Mathematics/GteIntrLine2AlignedBox2.h>
#include <GTEngine/Mathematics/GteIntrLine2Arc2.h>
#include <GTEngine/Mathematics/GteIntrLine2Circle2.h>
#include <GTEngine/Mathematics/GteIntrLine2Line2.h>
#include <GTEngine/Mathematics/GteIntrLine2OrientedBox2.h>
#include <GTEngine/Mathematics/GteIntrLine2Ray2.h>
#include <GTEngine/Mathematics/GteIntrLine2Segment2.h>
#include <GTEngine/Mathematics/GteIntrLine2Triangle2.h>
#include <GTEngine/Mathematics/GteIntrLine3AlignedBox3.h>
#include <GTEngine/Mathematics/GteIntrLine3Capsule3.h>
#include <GTEngine/Mathematics/GteIntrLine3Cone3.h>
#include <GTEngine/Mathematics/GteIntrLine3Cylinder3.h>
#include <GTEngine/Mathematics/GteIntrLine3Ellipsoid3.h>
#include <GTEngine/Mathematics/GteIntrLine3OrientedBox3.h>
#include <GTEngine/Mathematics/GteIntrLine3Plane3.h>
#include <GTEngine/Mathematics/GteIntrLine3Sphere3.h>
#include <GTEngine/Mathematics/GteIntrLine3Triangle3.h>
#include <GTEngine/Mathematics/GteIntrOrientedBox2Circle2.h>
#include <GTEngine/Mathematics/GteIntrOrientedBox2Cone2.h>
#include <GTEngine/Mathematics/GteIntrOrientedBox2OrientedBox2.h>
#include <GTEngine/Mathematics/GteIntrOrientedBox2Sector2.h>
#include <GTEngine/Mathematics/GteIntrOrientedBox3Cone3.h>
#include <GTEngine/Mathematics/GteIntrOrientedBox3Cylinder3.h>
#include <GTEngine/Mathematics/GteIntrOrientedBox3Frustum3.h>
#include <GTEngine/Mathematics/GteIntrOrientedBox3OrientedBox3.h>
#include <GTEngine/Mathematics/GteIntrOrientedBox3Sphere3.h>
#include <GTEngine/Mathematics/GteIntrPlane3Capsule3.h>
#include <GTEngine/Mathematics/GteIntrPlane3Circle3.h>
#include <GTEngine/Mathematics/GteIntrPlane3Cylinder3.h>
#include <GTEngine/Mathematics/GteIntrPlane3Ellipsoid3.h>
#include <GTEngine/Mathematics/GteIntrPlane3OrientedBox3.h>
#include <GTEngine/Mathematics/GteIntrPlane3Plane3.h>
#include <GTEngine/Mathematics/GteIntrPlane3Sphere3.h>
#include <GTEngine/Mathematics/GteIntrPlane3Triangle3.h>
#include <GTEngine/Mathematics/GteIntrRay2AlignedBox2.h>
#include <GTEngine/Mathematics/GteIntrRay2Arc2.h>
#include <GTEngine/Mathematics/GteIntrRay2Circle2.h>
#include <GTEngine/Mathematics/GteIntrRay2OrientedBox2.h>
#include <GTEngine/Mathematics/GteIntrRay2Ray2.h>
#include <GTEngine/Mathematics/GteIntrRay2Segment2.h>
#include <GTEngine/Mathematics/GteIntrRay2Triangle2.h>
#include <GTEngine/Mathematics/GteIntrRay3AlignedBox3.h>
#include <GTEngine/Mathematics/GteIntrRay3Capsule3.h>
#include <GTEngine/Mathematics/GteIntrRay3Cone3.h>
#include <GTEngine/Mathematics/GteIntrRay3Cylinder3.h>
#include <GTEngine/Mathematics/GteIntrRay3Ellipsoid3.h>
#include <GTEngine/Mathematics/GteIntrRay3OrientedBox3.h>
#include <GTEngine/Mathematics/GteIntrRay3Plane3.h>
#include <GTEngine/Mathematics/GteIntrRay3Sphere3.h>
#include <GTEngine/Mathematics/GteIntrRay3Triangle3.h>
#include <GTEngine/Mathematics/GteIntrSegment2AlignedBox2.h>
#include <GTEngine/Mathematics/GteIntrSegment2Arc2.h>
#include <GTEngine/Mathematics/GteIntrSegment2Circle2.h>
#include <GTEngine/Mathematics/GteIntrSegment2OrientedBox2.h>
#include <GTEngine/Mathematics/GteIntrSegment2Segment2.h>
#include <GTEngine/Mathematics/GteIntrSegment2Triangle2.h>
#include <GTEngine/Mathematics/GteIntrSegment3AlignedBox3.h>
#include <GTEngine/Mathematics/GteIntrSegment3Capsule3.h>
#include <GTEngine/Mathematics/GteIntrSegment3Cone3.h>
#include <GTEngine/Mathematics/GteIntrSegment3Cylinder3.h>
#include <GTEngine/Mathematics/GteIntrSegment3Ellipsoid3.h>
#include <GTEngine/Mathematics/GteIntrSegment3OrientedBox3.h>
#include <GTEngine/Mathematics/GteIntrSegment3Plane3.h>
#include <GTEngine/Mathematics/GteIntrSegment3Sphere3.h>
#include <GTEngine/Mathematics/GteIntrSegment3Triangle3.h>
#include <GTEngine/Mathematics/GteIntrSphere3Cone3.h>
#include <GTEngine/Mathematics/GteIntrSphere3Frustum3.h>
#include <GTEngine/Mathematics/GteIntrSphere3Sphere3.h>
#include <GTEngine/Mathematics/GteIntrSphere3Triangle3.h>
#include <GTEngine/Mathematics/GteIntrTriangle3OrientedBox3.h>
#include <GTEngine/Mathematics/GteTIQuery.h>

// NumericalMethods
#include <GTEngine/Mathematics/GteCholeskyDecomposition.h>
#include <GTEngine/Mathematics/GteCubicRootsQR.h>
#include <GTEngine/Mathematics/GteGaussNewtonMinimizer.h>
#include <GTEngine/Mathematics/GteGaussianElimination.h>
#include <GTEngine/Mathematics/GteIntegration.h>
#include <GTEngine/Mathematics/GteLCPSolver.h>
#include <GTEngine/Mathematics/GteLevenbergMarquardtMinimizer.h>
#include <GTEngine/Mathematics/GteLinearSystem.h>
#include <GTEngine/Mathematics/GteMinimize1.h>
#include <GTEngine/Mathematics/GteMinimizeN.h>
#include <GTEngine/Mathematics/GteOdeEuler.h>
#include <GTEngine/Mathematics/GteOdeImplicitEuler.h>
#include <GTEngine/Mathematics/GteOdeMidpoint.h>
#include <GTEngine/Mathematics/GteOdeRungeKutta4.h>
#include <GTEngine/Mathematics/GteOdeSolver.h>
#include <GTEngine/Mathematics/GteQuarticRootsQR.h>
#include <GTEngine/Mathematics/GteRootsBisection.h>
#include <GTEngine/Mathematics/GteRootsBrentsMethod.h>
#include <GTEngine/Mathematics/GteRootsPolynomial.h>
#include <GTEngine/Mathematics/GteSingularValueDecomposition.h>
#include <GTEngine/Mathematics/GteSymmetricEigensolver.h>
#include <GTEngine/Mathematics/GteSymmetricEigensolver2x2.h>
#include <GTEngine/Mathematics/GteSymmetricEigensolver3x3.h>
#include <GTEngine/Mathematics/GteUnsymmetricEigenvalues.h>

// Projection
#include <GTEngine/Mathematics/GteProjection.h>

// SIMD (removed due to compile issues + not needed currently)
// #if defined(__MSWINDOWS__) && !defined(MINGW)
// #include <GTEngine/Mathematics/MSW/GteIntelSSE.h>
// #include <GTEngine/Mathematics/MSW/GteCPUQueryInstructions.h>
// #endif

