// Copyright Epic Games, Inc. All Rights Reserved.

#include "CustomizableObjectPopulationEditorActions.h"
#include "CustomizableObjectPopulation.h"
#include "Framework/Commands/InputChord.h"

#define LOCTEXT_NAMESPACE "CustomizableObjectPopulationEditor"

void FCustomizableObjectPopulationEditorCommands::RegisterCommands()
{
	UI_COMMAND(Save, "Save", "Save the Population.", EUserInterfaceActionType::Button, FInputChord());
	UI_COMMAND(TestPopulation, "Test Population", "Generate intances in the viewport to test the Population", EUserInterfaceActionType::Button, FInputChord());
	UI_COMMAND(GenerateInstances, "Generate Instances", "Generate random instances generated by this Population", EUserInterfaceActionType::Button, FInputChord());
	UI_COMMAND(InspectSelectedInstance, "Inspect Instance", "Open the Customizable Object Instance Editor to inspect the selected instance in the preview viewport", EUserInterfaceActionType::Button, FInputChord());
	UI_COMMAND(InspectSelectedSkeletalMesh, "Inspect Skeletal Mesh", "Open the skeletal mesh editor to inspect the selected instance in the preview viewport", EUserInterfaceActionType::Button, FInputChord());
}

#undef LOCTEXT_NAMESPACE
