// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once 

#include "Engine/DataTable.h"
#include "Logging/LogMacros.h"
#include "MassCommonTypes.h"
#include "InstancedStruct.h"
#include "MassEntityTemplate.h"
#include "MassEntitySpawnPointsGeneratorBase.h"

#include "MassSpawnerTypes.generated.h"


DECLARE_LOG_CATEGORY_EXTERN(LogMassSpawner, Warning, All);

class APawn;
class UCurveFloat;
class UMassEntityConfigAsset;

USTRUCT()
struct FMassSpawnAuxData
{
	GENERATED_BODY()

	TArray<FTransform> Transforms;
};

USTRUCT()
struct FMassSpawnConfigBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Mass|Spawn", meta = (BaseStruct = "LWComponentData"))
	TArray<FInstancedStruct> AdditionalDataFragments;

	UPROPERTY(EditAnywhere, Category = "Mass|Spawn", meta = (ClampMin = 0, UIMin = 0))
	int32 MinNumber = 0;

	UPROPERTY(EditAnywhere, Category = "Mass|Spawn", meta = (ClampMin = 1, UIMin = 1))
	int32 MaxNumber = 1;

	UPROPERTY(EditAnywhere, Category = "Mass|Spawn", meta = (ClampMin = 0.0, UIMin = 0.0))
	float Radius = 0.f;

	friend uint32 GetTypeHash(const FMassSpawnConfigBase& Instance)
	{
		return HashCombine(HashCombine(GetTypeHash(Instance.MinNumber), GetTypeHash(Instance.MaxNumber)), GetTypeHash(Instance.Radius));
	}
};

/**
 * Describes an entity type to spawn.
 */
USTRUCT(BlueprintType)
struct FMassSpawnedEntityType
{
	GENERATED_BODY()

	/** Asset that describes the entity */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Mass|Spawn")
	TSoftObjectPtr<UMassEntityConfigAsset> EntityConfig;

	/** Proportion of the count that should be this agent type, (the proportions will be normalized with other sibling agent types) */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Mass|Spawn", meta = (ClampMin = 0.0f, UIMin = 0.0f))
	float Proportion = 1.0f;

	void UnloadEntityConfig()
	{
		EntityConfigPtr = nullptr;
		EntityConfig.ResetWeakPtr();
	}

	const UMassEntityConfigAsset* GetEntityConfig() const;
	UMassEntityConfigAsset* GetEntityConfig();

private:
	UPROPERTY()
	mutable UMassEntityConfigAsset* EntityConfigPtr = nullptr;
};

USTRUCT(BlueprintType)
struct FMassSpawnPointGenerator
{
	GENERATED_BODY()

	/** The Generator to use to generate the spawn the points */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Mass|Generator")
	TSubclassOf<UMassEntitySpawnPointsGeneratorBase> GeneratorClass;

	/** Proportion of the spawn points that should be generated by this generator, (the proportions will be normalized with other sibling generators) */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Mass|Generator", meta = (ClampMin = 0.0f, UIMin = 0.0f))
	float Proportion = 1.0f;

	/** Runtime value to know if we received the generated points for this generator */
	bool bPointsGenerated = false;
};

USTRUCT()
struct MASSSPAWNER_API FDataFragment_ReplicationTemplateID : public FLWComponentData
{
	GENERATED_BODY()

	UPROPERTY(Transient)
	FMassEntityTemplateID ID;
};
