// Copyright Epic Games, Inc. All Rights Reserved.

using System;
using System.IO;
using System.Collections.Generic;
using EpicGames.Core;


namespace UnrealBuildTool.Rules
{
	public class PixelStreaming : ModuleRules
	{
		const string PixelStreamingProgramsDirectory = "../../Engine/Plugins/Media/PixelStreaming/Resources";

		private void AddFolder(string Folder)
		{
			string DirectoryToAdd = new DirectoryInfo(PixelStreamingProgramsDirectory + "/ps-infra/" + Folder).FullName;

			if (!Directory.Exists(DirectoryToAdd))
			{
				return;
			}

			List<string> DependenciesToAdd = new List<string>();
			DependenciesToAdd.AddRange(Directory.GetFiles(DirectoryToAdd, "*.*", SearchOption.AllDirectories));

			List<string> PathsToIgnore = new List<string>();
			PathsToIgnore.Add(new DirectoryInfo(DirectoryToAdd + "/node_modules").FullName);
			PathsToIgnore.Add(new DirectoryInfo(DirectoryToAdd + "/logs").FullName);
			PathsToIgnore.Add(new DirectoryInfo(DirectoryToAdd + "/platform_scripts/cmd/node").FullName);
			PathsToIgnore.Add(new DirectoryInfo(DirectoryToAdd + "/platform_scripts/cmd/coturn").FullName);
			PathsToIgnore.Add(new DirectoryInfo(DirectoryToAdd + "/platform_scripts/bash/node").FullName);

			// Go through each file/folder in the WebServers and selectively choose which ones we wish to package.
			foreach(var DependencySource in DependenciesToAdd)
			{
				// We want to skip packaging the above directories as they are all generated by running scripts
				bool bSkip = false;
				foreach(var PathToIgnore in PathsToIgnore)
				{
					if(DependencySource.StartsWith(PathToIgnore))
					{
						bSkip = true;
						continue;
					}
				}

				// If we are not skipping, we want to add this to our packaged output
				if(!bSkip)
				{
					RuntimeDependencies.Add(DependencySource, StagedFileType.NonUFS);
				}
			}
		}

		public PixelStreaming(ReadOnlyTargetRules Target) : base(Target)
		{
			// use private PCH to include lots of WebRTC headers
			PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
			PrivatePCHHeaderFile = "Private/PCH.h";

			var EngineDir = Path.GetFullPath(Target.RelativeEnginePath);

			// This is so for game projects using our public headers don't have to include extra modules they might not know about.
			PublicDependencyModuleNames.AddRange(new string[]
			{
				"ApplicationCore",
				"InputDevice",
				"WebRTC"
			});

			// NOTE: General rule is not to access the private folder of another module
			PrivateIncludePaths.AddRange(new string[]
			{
				Path.Combine(EngineDir, "Source/Runtime/AudioMixer/Private"),
			});

			// WebRTC third party includes (just libyuv for colour format conversions for now)
			PublicIncludePaths.AddRange(new string[]
				{
					Path.Combine(EngineDir, "Source/ThirdParty/WebRTC/4147/Include/third_party/libyuv/include"),
				});

			PrivateDependencyModuleNames.AddRange(new string[]
			{
				"Core",
				"CoreUObject",
				"Engine",
				"EngineSettings",
				"InputCore",
				"Json",
				"Renderer",
				"RenderCore",
				"RHI",
				"Slate",
				"SlateCore",
				"AudioMixer",
				"WebRTC",
				"WebSockets",
				"Sockets",
				"MediaUtils",
				"DeveloperSettings",
				"AVEncoder",
				"PixelStreamingShaders"
			});

			PrivateDependencyModuleNames.Add("VulkanRHI");
			AddEngineThirdPartyPrivateStaticDependencies(Target, "Vulkan", "CUDA");

			if (Target.IsInPlatformGroup(UnrealPlatformGroup.Windows))
			{
				PrivateDependencyModuleNames.Add("D3D11RHI");
				PrivateDependencyModuleNames.Add("D3D12RHI");

				AddEngineThirdPartyPrivateStaticDependencies(Target, "DX11", "DX12");
			}

			// When we build a Game target we also package the servers with it as runtime dependencies
			if(Target.Type == TargetType.Game)
			{
				AddFolder("SignallingWebServer");
				AddFolder("Matchmaker");
				AddFolder("SFU");

				RuntimeDependencies.Add("$(PluginDir)/Resources/get_ps_servers.bat", StagedFileType.NonUFS);
				RuntimeDependencies.Add("$(PluginDir)/Resources/get_ps_servers.sh", StagedFileType.NonUFS);
			}
		}
	}
}
