// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "HAL/Platform.h"
#include "Containers/Map.h"
#include "Containers/Array.h"

namespace mu
{
	/** Handle used to identify separate resources generated by mutable: images and meshes included in instances. */
    typedef uint64 FResourceID;

    /** Unique identifier for images provided by code using mutable, of which mutable doesn't know much. */
    typedef FString FExternalImageID;

}


//
template<typename T>
inline uint32 GetTypeHash(const TArray<T>& Key)
{
	uint32 Hash = 0;
	for (const T& e : Key)
	{
		Hash = HashCombine(Hash, GetTypeHash(e));
	}
	return Hash;
}


//
template<typename K, typename V>
inline bool operator==(const TMap<K,V>& A, const TMap<K,V>& B )
{	
	return A.OrderIndependentCompareEqual(B);
}


